

export const soulbindDB = [
            {
                "id": 328266,
                "names": {
                    "en": "Combat Meditation",
                    "cn": "放下过去",
                },
                "icon": "spell_animabastion_buff.jpg",
                "soulbind": "Pelagos",
                "position": [0, 1], 
                "renown": 0,
                "active": false,
                "stat_bonus": {},
            },
            {
            
                "names": {
                    "en": "Finesse Conduit",
                    "cn": "",
                },
                "icon": "finesse.jpg",
                "soulbind": "Pelagos",
                "position": [1, 0], 
                "renown": 0,
                "active": false,
                "stat_bonus": {},
            },
            {
                "names": {
                    "en": "Endurance Conduit",
                    "cn": "",
                },
                "icon": "endurance.jpg",
                "soulbind": "Pelagos",
                "position": [1, 1], 
                "renown": 0,
                "active": false,
                "stat_bonus": {},
            },
            {
                "names": {
                    "en": "Potency Conduit",
                    "cn": "",
                },
                "icon": "potency.jpg",
                "soulbind": "Pelagos",
                "position": [1, 2], 
                "renown": 0,
                "active": false,
                "stat_bonus": {},
            },
            {
                "id": 328261,
                "names": {
                    "en": "Focusing Mantra",
                    "cn": "耐心之瓶",
                },
                "icon": "spell_arcane_focusedpower.jpg",
                "soulbind": "Pelagos",
                "position": [2, 0], 
                "renown": 0,
                "active": false,
                "stat_bonus": {},
            },
            {
                "id": 0,
                "names": {
                    "en": "Road of Trials",
                    "cn": "耐心之瓶",
                },
                "icon": "achievement_guildperk_havegroup-willtravel.jpg",
                "soulbind": "Pelagos",
                "position": [2, 1], 
                "renown": 0,
                "active": false,
                "stat_bonus": {},
            },
            {
                "id": 329777,
                "names": {
                    "en": "Phial of Patience",
                    "cn": "耐心之瓶",
                },
                "icon": "inv_gizmo_khoriumpowercore.jpg",
                "soulbind": "Pelagos",
                "position": [2, 2], 
                "renown": 0,
                "active": false,
                "stat_bonus": {},
            },
            {
                "id": 0,
                "names": {
                    "en": "Endurance Conduit",
                    "cn": "耐心之瓶",
                },
                "icon": "endurance.jpg",
                "soulbind": "Pelagos",
                "position": [3, 1], 
                "renown": 0,
                "active": false,
                "stat_bonus": {},
            },
            {
                "id": 0,
                "names": {
                    "en": "Bond of Friendship",
                    "cn": "耐心之瓶",
                },
                "icon": "ability_hunter_displacement.jpg",
                "soulbind": "Pelagos",
                "position": [4, 0], 
                "renown": 0,
                "active": false,
                "stat_bonus": {},
            },
            {
                "id": 0,
                "names": {
                    "en": "Cleansed Vestments",
                    "cn": "耐心之瓶",
                },
                "icon": "inv_misc_bag_14.jpg",
                "soulbind": "Pelagos",
                "position": [4, 2], 
                "renown": 0,
                "active": false,
                "stat_bonus": {},
            },
            {
                "id": 0,
                "names": {
                    "en": "Potency Conduit",
                    "cn": "耐心之瓶",
                },
                "icon": "potency.jpg",
                "soulbind": "Pelagos",
                "position": [5, 1], 
                "renown": 0,
                "active": false,
                "stat_bonus": {},
            },
            {
                "id": 0,
                "names": {
                    "en": "Endurance Conduit",
                    "cn": "耐心之瓶",
                },
                "icon": "endurance.jpg",
                "soulbind": "Pelagos",
                "position": [6, 0], 
                "renown": 0,
                "active": false,
                "stat_bonus": {},
            },
            {
                "id": 0,
                "names": {
                    "en": "Finesse Conduit",
                    "cn": "耐心之瓶",
                },
                "icon": "finesse.jpg",
                "soulbind": "Pelagos",
                "position": [6, 2], 
                "renown": 0,
                "active": false,
                "stat_bonus": {},
            },
            {
                "id": 328257,
                "names": {
                    "en": "Let Go of the Past",
                    "cn": "耐心之瓶",
                },
                "icon": "ability_hunter_readiness.jpg",
                "soulbind": "Pelagos",
                "position": [7, 1], 
                "renown": 0,
                "active": false,
                "stat_bonus": {},
            }]