export const TOGGLE_CONTENT = "TOGGLE_CONTENT";
export const TOGGLE_GAMETYPE = "TOGGLE_GAMETYPE";
export const TOGGLE_PLAYERSETTINGS = "TOGGLE_PLAYERSETTINGS";
export const TOGGLE_PATRONSTATUS = "TOGGLE_PLAYERSETTINGS";
export const TOGGLE_COOLDOWNPLANNERTHEME = "TOGGLE_COOLDOWNPLANNERTHEME";