export const evokerBaseTalents = [
  /* ------------------------------------------ First Row ----------------------------------------- */
  {
    guid: 358385,
    name: "Landslide",
    icon: require("Images/Talents/ability_earthen_pillar.jpg").default,

    row: 0,
    pos: 1,
    ranks: 1,
    type: "Ability",
    connections: [369913],
  },
  {
    guid: 363916,
    name: "Obsidian Scales",
    icon: require("Images/Talents/inv_artifact_dragonscales.jpg").default,
    row: 0,
    pos: 3,
    ranks: 1,
    type: "Ability",
    connections: [370897],
  },
  {
    guid: 365585,
    name: "Expunge",
    icon: require("Images/Talents/ability_evoker_fontofmagic_green.jpg").default,
    row: 0,
    pos: 5,
    ranks: 1,
    type: "Ability",
    connections: [360995],
  },
  /* ----------------------------------------- Second Row ----------------------------------------- */
  {
    guid: 369913,
    name: "Natural Convergence",
    icon: require("Images/Talents/spell_frost_frostblast.jpg").default,
    row: 1,
    pos: 1,
    ranks: 1,
    type: "Talent",
    connections: [375528, 375520, 351338],
  },
  {
    guid: 370897,
    name: "Permeating Chill",
    icon: require("Images/Talents/spell_frost_coldhearted.jpg").default,
    row: 1,
    pos: 3,
    ranks: 1,
    type: "Talent",
    connections: [375406, 375520, 375554],
  },
  {
    guid: 360995,
    name: "Verdant Embrace",
    icon: require("Images/Talents/ability_evoker_rescue.jpg").default,
    row: 1,
    pos: 5,
    ranks: 1,
    type: "Ability",
    connections: [375554, 372469],
  },
  /* ------------------------------------------ Third Row ----------------------------------------- */
  {
    guid: 375528,
    name: "Forger of Mountains",
    icon: require("Images/Talents/ability_earthen_pillar.jpg").default,
    row: 2,
    pos: 0,
    ranks: 1,
    type: "Talent",
    connections: [],
  },
  {
    guid: 375520,
    name: "Innate Magic",
    icon: require("Images/Talents/ability_evoker_innatemagic4.jpg").default,
    row: 2,
    pos: 2,
    ranks: 2,
    type: "Talent",
    connections: [351338, 371806, 368838, 375443],
  },
  {
    guid: 375406,
    name: "Obsidian Bulwark",
    icon: require("Images/Talents/inv_shield_1h_revenantfire_d_01.jpg").default,
    row: 2,
    pos: 3,
    ranks: 1,
    type: "Talent",
    connections: [],
  },
  {
    guid: 375554,
    name: "Enkindled",
    icon: require("Images/Talents/ability_evoker_livingflame.jpg").default,
    row: 2,
    pos: 4,
    ranks: 2,
    type: "Talent",
    connections: [368838, 375443, 375556, 374251],
  },
  {
    guid: 372469,
    name: "Scarlet Adaptation",
    icon: require("Images/Talents/inv_bijou_red.jpg").default,
    row: 2,
    pos: 6,
    ranks: 1,
    type: "Talent",
    connections: [],
  },
  /* ----------------------------------------- Fourth Row ----------------------------------------- */
  {
    guid: 351338,
    name: "Quell",
    icon: require("Images/Talents/ability_evoker_quell.jpg").default,
    row: 3,
    pos: 1,
    ranks: 1,
    type: "Ability",
    connections: [369990],
  },
  {
    guid: 371806,
    name: "Recall",
    icon: require("Images/Talents/ability_evoker_recall.jpg").default,
    row: 3,
    pos: 2,
    ranks: 1,
    type: "Talent",
    connections: [376164, 376166],
  },

  {
    guid: 368838,
    name: "Heavy Wingbeats",
    icon: require("Images/Talents/ability_racial_wingbuffet.jpg").default,
    row: 3,
    pos: 3,
    ranks: 1,
    type: "Talent",
    connections: [],
  },
  {
    guid: 375443,
    name: "Clobbering Sweep",
    icon: require("Images/Talents/ability_racial_tailswipe.jpg").default,
    row: 3,
    pos: 3,
    ranks: 1,
    type: "Talent",
    connections: [],
  },

  {
    guid: 375556,
    name: "Tailwind",
    icon: require("Images/Talents/ability_skyreach_wind.jpg").default,
    row: 3,
    pos: 4,
    ranks: 1,
    type: "Talent",
    connections: [375517],
  },
  {
    guid: 374251,
    name: "Cauterizing Flame",
    icon: require("Images/Talents/ability_evoker_fontofmagic_red.jpg").default,
    row: 3,
    pos: 5,
    ranks: 1,
    type: "Ability",
    connections: [376930, 360806],
  },
  /* ------------------------------------------ Fifth Row ----------------------------------------- */
  {
    guid: 369990,
    name: "Ancient Flame",
    icon: require("Images/Talents/inv_elemental_mote_fire01.jpg").default,
    row: 4,
    pos: 0,
    ranks: 1,
    type: "Talent",
    connections: [],
  },
  {
    guid: 376164,
    name: "Instinctive Arcana",
    icon: require("Images/Talents/spell_arcane_studentofmagic.jpg").default,
    row: 4,
    pos: 1,
    ranks: 2,
    type: "Talent",
    connections: [375510],
  },

  {
    guid: 370553,
    name: "Tip the Scales",
    icon: require("Images/Talents/ability_evoker_tipthescales.jpg").default,
    row: 4,
    pos: 3,
    ranks: 1,
    type: "Ability",
    connections: [376166, 375544, 375517],
  },

  {
    guid: 376930,
    name: "Attuned to the Dream",
    icon: require("Images/Talents/ability_rogue_imrovedrecuperate.jpg").default,
    row: 4,
    pos: 5,
    ranks: 2,
    type: "Talent",
    connections: [370886],
  },
  {
    guid: 360806,
    name: "Sleep Walk",
    icon: require("Images/Talents/ability_xavius_dreamsimulacrum.jpg").default,
    row: 4,
    pos: 6,
    ranks: 1,
    type: "Ability",
    connections: [],
  },
  /* ------------------------------------------ Sixth Row ----------------------------------------- */
  {
    guid: 376166,
    name: "Draconic Legacy",
    icon: require("Images/Talents/inv_helm_mail_dracthyrquest_b_02.jpg").default,
    row: 5,
    pos: 2,
    ranks: 2,
    type: "Talent",
    connections: [375510, 375542],
  },
  {
    guid: 375544,
    name: "Inherent Resistance",
    icon: require("Images/Talents/inv_misc_rubysanctum1.jpg").default,
    row: 5,
    pos: 3,
    ranks: 2,
    type: "Talent",
    connections: [369459],
  },
  {
    guid: 375517,
    name: "Extended Flight",
    icon: require("Images/Talents/ability_evoker_hover.jpg").default,
    row: 5,
    pos: 4,
    ranks: 2,
    type: "Talent",
    connections: [387341, 387761],
  },
  {
    guid: 370886,
    name: "Bountiful Bloom",
    icon: require("Images/Talents/ability_evoker_emeraldblossom.jpg").default,
    row: 5,
    pos: 5,
    ranks: 1,
    type: "Talent",
    connections: [387761],
  },
  /* ----------------------------------------- Seventh Row ---------------------------------------- */
  {
    guid: 375510,
    name: "Blast Furnace",
    icon: require("Images/Talents/ability_evoker_firebreath.jpg").default,
    row: 6,
    pos: 1,
    ranks: 2,
    type: "Talent",
    connections: [368432, 369909, 372048],
  },
  {
    guid: 375542,
    name: "Exuberance",
    icon: require("Images/Talents/ability_evoker_hover2.jpg").default,
    row: 6,
    pos: 2,
    ranks: 1,
    type: "Talent",
    connections: [],
  },
  {
    guid: 369459,
    name: "Source of Magic",
    icon: require("Images/Talents/ability_evoker_blue_01.jpg").default,
    row: 6,
    pos: 3,
    ranks: 1,
    type: "Ability",
    connections: [387787, 370665],
  },
  {
    guid: 387341,
    name: "Walloping Blow",
    icon: require("Images/Talents/inv_misc_monsterscales_06.jpg").default,
    row: 6,
    pos: 4,
    ranks: 1,
    type: "Talent",
    connections: [],
  },
  {
    guid: 387761,
    name: "Panacea",
    icon: require("Images/Talents/ability_druid_protectionofthegrove.jpg").default,
    row: 6,
    pos: 5,
    ranks: 1,
    type: "Talent",
    connections: [370665, 375561, 374348],
  },
  /* ----------------------------------------- Eighth Row ----------------------------------------- */
  {
    guid: 368432,
    name: "Unravel",
    icon: require("Images/Talents/ability_evoker_unravel.jpg").default,
    row: 7,
    pos: 0,
    ranks: 1,
    type: "Ability",
    connections: [369939],
  },
  {
    guid: 369909,
    name: "Protracted Talons",
    icon: require("Images/Talents/ability_evoker_azurestrike.jpg").default,
    row: 7,
    pos: 1,
    ranks: 1,
    type: "Talent",
    connections: [369939],
  },
  {
    guid: 372048,
    name: "Oppressing Roar",
    icon: require("Images/Talents/ability_evoker_oppressingroar.jpg").default,
    row: 7,
    pos: 2,
    ranks: 1,
    type: "Ability",
    connections: [369939, 365933, 374346],
  },
  {
    guid: 387787,
    name: "Regenerative Magic",
    icon: require("Images/Talents/spell_frost_manarecharge.jpg").default,
    row: 7,
    pos: 3,
    ranks: 1,
    type: "Talent",
    connections: [],
  },
  {
    guid: 370665,
    name: "Rescue",
    icon: require("Images/Talents/ability_evoker_flywithme.jpg").default,
    row: 7,
    pos: 4,
    ranks: 1,
    type: "Ability",
    connections: [365933, 370888],
  },
  {
    guid: 375561,
    name: "Lush Growth",
    icon: require("Images/Talents/inv_staff_2h_bloodelf_c_01.jpg").default,
    row: 7,
    pos: 5,
    ranks: 2,
    type: "Talent",
    connections: [374227],
  },
  {
    guid: 374348,
    name: "Renewing Blaze",
    icon: require("Images/Talents/ability_evoker_masterylifebinder_red.jpg").default,
    row: 7,
    pos: 6,
    ranks: 1,
    type: "Ability",
    connections: [375574, 375577],
  },

  /* ------------------------------------------ Ninth Row ----------------------------------------- */
  {
    guid: 369939,
    name: "Leaping Flames",
    icon: require("Images/Talents/spell_fire_flare.jpg").default,
    row: 8,
    pos: 1,
    ranks: 1,
    type: "Talent",
    connections: [371032],
  },
  {
    guid: 374346,
    name: "Overawe",
    icon: require("Images/Talents/ability_evoker_oppressingroar2.jpg").default,
    row: 8,
    pos: 2,
    ranks: 1,
    type: "Talent",
    connections: [],
  },
  {
    guid: 365933,
    name: "Aerial Mastery",
    icon: require("Images/Talents/ability_evoker_aerialmastery.jpg").default,
    row: 8,
    pos: 3,
    ranks: 1,
    type: "Talent",
    connections: [374968],
  },
  {
    guid: 370888,
    name: "Twin Guardian",
    icon: require("Images/Talents/ability_skyreach_shielded.jpg").default,
    row: 8,
    pos: 4,
    ranks: 1,
    type: "Talent",
    connections: [374227],
  },

  {
    guid: 375574,
    name: "Foci of Life",
    icon: require("Images/Talents/spell_fire_incinerate.jpg").default,
    row: 8,
    pos: 6,
    ranks: 1,
    type: "Talent",
    connections: [374227],
  },
  {
    guid: 375577,
    name: "Fire Within",
    icon: require("Images/Talents/item_sparkofragnoros.jpg").default,
    row: 8,
    pos: 6,
    ranks: 1,
    type: "Talent",
    connections: [374227],
  },

  /* ------------------------------------------ Tenth Row ----------------------------------------- */
  {
    guid: 371032,
    name: "Terror of the Skies",
    icon: require("Images/Talents/ability_evoker_terroroftheskies.jpg").default,
    row: 9,
    pos: 1,
    ranks: 1,
    type: "Talent",
    connections: [],
  },
  {
    guid: 374968,
    name: "Time Spiral",
    icon: require("Images/Talents/ability_evoker_timespiral.jpg").default,
    row: 9,
    pos: 3,
    ranks: 1,
    type: "Ability",
    connections: [],
  },
  {
    guid: 374227,
    name: "Zephyr",
    icon: require("Images/Talents/ability_evoker_hoverblack.jpg").default,
    row: 9,
    pos: 5,
    ranks: 1,
    type: "Ability",
    connections: [],
  },
];
