export const soulbindDB = [
  // Kyrian Soulbinds
  // Pelagos
  {
    id: 328266,
    names: {
      en: "Combat Meditation",
      cn: "放下过去",
      fr: "Méditation de combat",
      ru: "Боевая медитация",
    },
    icon: "spell_animabastion_buff.jpg",
    soulbind: "Pelagos",
    position: [0, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 983921,
    names: {
      en: "Finesse Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Pelagos",
    position: [1, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Finesse Conduit",
  },
  {
    id: 903132,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Pelagos",
    position: [1, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 8903278612,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Pelagos",
    position: [1, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Potency Conduit",
    slotted_id: -1,
  },
  {
    id: 328261,
    names: {
      en: "Focusing Mantra",
      cn: "耐心之瓶",
      fr: "Mantra de concentration",
      ru: "Мантра сосредоточения",
    },
    icon: "spell_arcane_focusedpower.jpg",
    soulbind: "Pelagos",
    position: [2, 0],
    renown: 3,
    active: false,
    stat_bonus: {},
  },
  {
    id: 329786,
    names: {
      en: "Road of Trials",
      cn: "耐心之瓶",
      fr: "Calvaire",
      ru: "Дорога испытаний",
    },
    icon: "achievement_guildperk_havegroup-willtravel.jpg",
    soulbind: "Pelagos",
    position: [2, 1],
    renown: 3,
    active: false,
    stat_bonus: {},
  },
  {
    id: 329777,
    names: {
      en: "Phial of Patience",
      cn: "耐心之瓶",
      fr: "Flasque de patience",
      ru: "Флакон терпения",
    },
    icon: "inv_gizmo_khoriumpowercore.jpg",
    soulbind: "Pelagos",
    position: [2, 2],
    renown: 3,
    active: false,
    stat_bonus: {},
  },
  {
    id: 8901231,
    names: {
      en: "Endurance Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Pelagos",
    position: [3, 1],
    renown: 7,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 328265,
    names: {
      en: "Bond of Friendship",
      cn: "耐心之瓶",
      fr: "Lien d’amitié",
      ru: "Узы дружбы",
    },
    icon: "ability_hunter_displacement.jpg",
    soulbind: "Pelagos",
    position: [4, 0],
    renown: 10,
    active: false,
    stat_bonus: {},
  },
  {
    id: 328263,
    names: {
      en: "Cleansed Vestments",
      cn: "耐心之瓶",
      fr: "Habits purifiés",
      ru: "Очищенные одеяния",
    },
    icon: "inv_misc_bag_14.jpg",
    soulbind: "Pelagos",
    position: [4, 2],
    renown: 10,
    active: false,
    stat_bonus: {},
  },
  {
    id: 7178321,
    names: {
      en: "Potency Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Pelagos",
    position: [5, 1],
    renown: 21,
    active: false,
    stat_bonus: {},
    type: "Potency Conduit",
    slotted_id: -1,
  },
  {
    id: 980109,
    names: {
      en: "Endurance Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Pelagos",
    position: [6, 0],
    renown: 25,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 8903212,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Pelagos",
    position: [6, 2],
    renown: 25,
    active: false,
    stat_bonus: {},
    type: "Finesse Conduit",
  },
  {
    id: 328257,
    names: {
      en: "Let Go of the Past",
      cn: "耐心之瓶",
      fr: "Renoncement au passé",
      ru: "Забудь прошлое",
    },
    icon: "ability_hunter_readiness.jpg",
    soulbind: "Pelagos",
    position: [7, 1],
    renown: 30,
    active: false,
    stat_bonus: {},
  },

  // Kleia
  {
    id: 329791,
    names: {
      en: "Valiant Strikes",
      cn: "骁勇打击",
      fr: "Frappes vaillantes",
      ru: "Храбрые удары",
    },
    icon: "spell_holy_prayerofspirit.jpg",
    soulbind: "Kleia",
    position: [0, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 1000839210,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Kleia",
    position: [1, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Potency Conduit",
    slotted_id: -1,
  },
  {
    id: 1000839211,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Kleia",
    position: [1, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 334066,
    names: {
      en: "Mentorship",
      cn: "师徒一心",
      fr: "Mentorat",
      ru: "Наставничество",
    },
    icon: "achievement_reputation_05.jpg",
    soulbind: "Kleia",
    position: [2, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 329776,
    names: {
      en: "Ascendant Phial",
      cn: "晋升之瓶",
      fr: "Flasque d’ascendant",
      ru: "Флакон перерожденного",
    },
    icon: "inv_alchemy_elixir_02.jpg",
    soulbind: "Kleia",
    position: [2, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 2000839211,
    names: {
      en: "Finesse Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Kleia",
    position: [3, 1],
    renown: 9,
    active: false,
    stat_bonus: {},
  },
  {
    id: 329784,
    names: {
      en: "Cleansing Rites",
      cn: "净化仪式",
      fr: "Rites purificatoires",
      ru: "Ритуалы очищения",
    },
    icon: "spell_magic_magearmor.jpg",
    soulbind: "Kleia",
    position: [4, 0],
    renown: 13,
    active: false,
    stat_bonus: {},
  },
  {
    id: 328258,
    names: {
      en: "Ever Forward",
      cn: "更进一步",
      fr: "Proactivité",
      ru: "Только вперед",
    },
    icon: "spell_frost_wisp.jpg",
    soulbind: "Kleia",
    position: [4, 2],
    renown: 13,
    active: false,
    stat_bonus: {},
  },
  {
    id: 1000839212,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Kleia",
    position: [5, 1],
    renown: 18,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 1000839213,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Kleia",
    position: [6, 0],
    renown: 28,
    active: false,
    stat_bonus: {},
    type: "Potency Conduit",
    slotted_id: -1,
  },
  {
    id: 1000839214,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Kleia",
    position: [6, 1],
    renown: 28,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 2000839212,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Kleia",
    position: [6, 2],
    renown: 28,
    active: false,
    stat_bonus: {},
  },
  {
    id: 329779,
    names: {
      en: "Bearer's Pursuit",
      cn: "载魂者的追击",
      fr: "Poursuite du porteur",
      ru: "Преследование носителя",
    },
    icon: "inv_boots_plate_05.jpg",
    soulbind: "Kleia",
    position: [7, 0],
    renown: 34,
    active: false,
    stat_bonus: {},
  },
  {
    id: 329778,
    names: {
      en: "Pointed Courage",
      cn: "勇气外露",
      fr: "Courage exemplaire",
      ru: "Демонстративная отвага",
    },
    icon: "ability_hunter_displacement.jpg",
    soulbind: "Kleia",
    position: [7, 1],
    renown: 34,
    active: false,
    stat_bonus: {},
  },
  {
    id: 329781,
    names: {
      en: "Resonant Accolades",
      cn: "共鸣赞誉",
      fr: "Accolades résonnantes",
      ru: "Гулкая похвальба",
    },
    icon: "spell_holy_mindvision.jpg",
    soulbind: "Kleia",
    position: [7, 2],
    renown: 34,
    active: false,
    stat_bonus: {},
  },

  // Mikanikos
  {
    id: 333950,
    names: {
      en: "Bron's Call to Action",
      cn: "行动的召唤：布隆",
      fr: "Appel à l’action de Bron",
      ru: "Призыв к действию: Брон",
    },
    icon: "ui_sigil_kyrian.jpg",
    soulbind: "Mikanikos",
    position: [0, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 3000839211,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Mikanikos",
    position: [1, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Potency Conduit",
    slotted_id: -1,
  },
  {
    id: 3000839213,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Mikanikos",
    position: [1, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 331609,
    names: {
      en: "Forgelite Filter",
      cn: "掌炉大师的滤网",
      fr: "Additif chargé",
      ru: "Фильтр автоматурга",
    },
    icon: "inv_alchemy_lightbloodelixir.jpg",
    soulbind: "Mikanikos",
    position: [2, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 331610,
    names: {
      en: "Charged Additive",
      cn: "充能添加剂",
      fr: "Filtre du forgelite",
      ru: "Заряженная добавка",
    },
    icon: "inv_potion_105.jpg",
    soulbind: "Mikanikos",
    position: [2, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 3000839214,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Mikanikos",
    position: [3, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 331726,
    names: {
      en: "Regenerating Materials",
      cn: "再生材料",
      fr: "Régénération des matériaux",
      ru: "Регенерирующие материалы",
    },
    icon: "inv_misc_enchantedpearlf.jpg",
    soulbind: "Mikanikos",
    position: [4, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 331725,
    names: {
      en: "Resilient Plumage",
      cn: "强韧之羽",
      fr: "Plumage résistant",
      ru: "Прочные перья",
    },
    icon: "achievement_legionpvp4tier1.jpg",
    soulbind: "Mikanikos",
    position: [4, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 3000839215,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Mikanikos",
    position: [5, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 3000839216,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Mikanikos",
    position: [6, 0],
    renown: 29,
    active: false,
    stat_bonus: {},
    type: "Potency Conduit",
    slotted_id: -1,
  },
  {
    id: 3000839217,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Mikanikos",
    position: [6, 1],
    renown: 29,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 3000839218,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Mikanikos",
    position: [6, 2],
    renown: 29,
    active: false,
    stat_bonus: {},
  },
  {
    id: 331611,
    names: {
      en: "Soulsteel Clamps",
      cn: "灵钢之钳",
      fr: "Pinces en acier d’âme",
      ru: "Клещи из духостали",
    },
    icon: "inv_misc_enggizmos_05.jpg",
    soulbind: "Mikanikos",
    position: [7, 0],
    renown: 31,
    active: false,
    stat_bonus: {},
  },
  {
    id: 333935,
    names: {
      en: "Hammer of Genesis",
      cn: "源生重槌",
      fr: "Marteau de la genèse",
      ru: "Молот творения",
    },
    icon: "spell_paladin_lightshammer.jpg",
    soulbind: "Mikanikos",
    position: [7, 1],
    renown: 31,
    active: false,
    stat_bonus: {},
  },
  {
    id: 331612,
    names: {
      en: "Sparkling Driftglobe Core",
      cn: "闪亮的流波之球核心",
      fr: "Noyau de globe de poussée étincelant",
      ru: "Искрящееся ядро дрейфующего шара",
    },
    icon: "inv_jewelcrafting_80_cutgem02_blue.jpg",
    soulbind: "Mikanikos",
    position: [7, 2],
    renown: 31,
    active: false,
    stat_bonus: {},
  },
  // Marileth
  {
    id: 323074,
    names: {
      en: "Volatile Solvent",
      cn: "不稳定的溶液",
      fr: "Solvant volatil",
      ru: "Нестабильный растворитель",
    },
    icon: "inv_misc_food_legion_gooslime_pool.jpg",
    soulbind: "Marileth",
    position: [0, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 4000839211,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Marileth",
    position: [1, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Potency Conduit",
    slotted_id: -1,
  },
  {
    id: 3000839212,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Marileth",
    position: [1, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 3000839213,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Marileth",
    position: [1, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 323091,
    names: {
      en: "Ooz's Frictionless Coating",
      cn: "乌兹的和谐覆层",
      fr: "Enrobage glissant de Limus",
      ru: "Гладкое покрытие Склизя",
    },
    icon: "inv_maldraxxusslime_green.jpg",
    soulbind: "Marileth",
    position: [2, 0],
    renown: 3,
    active: false,
    stat_bonus: {},
  },
  {
    id: 323089,
    names: {
      en: "Travel with Bloop",
      cn: "与吵吵一起旅行",
      fr: "Voyager avec Bloup",
      ru: "Путешествие с Блупом",
    },
    icon: "inv_maldraxxusslime_red.jpg",
    soulbind: "Marileth",
    position: [2, 1],
    renown: 3,
    active: false,
    stat_bonus: {},
  },
  {
    id: 323090,
    names: {
      en: "Plaguey's Preemptive Strike",
      cn: "烦烦的先发制人",
      fr: "Frappe préventive de Pesti",
      ru: "Превентивный удар Чумника",
    },
    icon: "inv_maldraxxusslime_yellow.jpg",
    soulbind: "Marileth",
    position: [2, 2],
    renown: 3,
    active: false,
    stat_bonus: {},
  },
  {
    id: 3000839214,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Marileth",
    position: [3, 1],
    renown: 9,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 323079,
    names: {
      en: "Kevin's Keyring",
      cn: "凯文的钥匙圈",
      fr: "Trousseau de clés de Kevin",
      ru: "Связка ключей Кевина",
    },
    icon: "inv_maldraxxusslime_purple.jpg",
    soulbind: "Marileth",
    position: [4, 0],
    renown: 10,
    active: false,
    stat_bonus: {},
  },
  {
    id: 323081,
    names: {
      en: "Plagueborn Cleansing Slime",
      cn: "灾裔清洁软泥",
      fr: "Gelée purificatrice peste-née",
      ru: "Чумной слизнюк-чистильщик",
    },
    icon: "inv_maldraxxusslime_plague.jpg",
    soulbind: "Marileth",
    position: [4, 2],
    renown: 10,
    active: false,
    stat_bonus: {},
  },
  {
    id: 3000839215,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Marileth",
    position: [5, 1],
    renown: 21,
    active: false,
    stat_bonus: {},
    type: "Potency Conduit",
    slotted_id: -1,
  },
  {
    id: 3000839216,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Marileth",
    position: [6, 0],
    renown: 25,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 3000839217,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Marileth",
    position: [6, 2],
    renown: 25,
    active: false,
    stat_bonus: {},
  },
  {
    id: 323095,
    names: {
      en: "Ultimate Form",
      cn: "终极形态",
      fr: "Forme ultime",
      ru: "Совершенный облик",
    },
    icon: "spell_shadow_zdemonformgreen.jpg",
    soulbind: "Marileth",
    position: [7, 1],
    renown: 30,
    active: false,
    stat_bonus: {},
  },
  // Emeni
  {
    id: 342156,
    names: {
      en: "Lead by Example",
      cn: "具化构造体",
      fr: "Incarnation d’assemblage",
      ru: "Кадавр мечты",
    },
    icon: "trade_archaeology_vrykul_runestick.jpg",
    soulbind: "Emeni",
    position: [0, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 6000839211,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Emeni",
    position: [1, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Potency Conduit",
    slotted_id: -1,
  },
  {
    id: 6000839212,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Emeni",
    position: [1, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 323921,
    names: {
      en: "Emeni's Magnificent Skin",
      cn: "艾米妮的优美之皮",
      fr: "Peau sublime d’Éméni",
      ru: "Великолепная кожа Эмени",
    },
    icon: "inv_helm_crown_c_01_black.jpg",
    soulbind: "Emeni",
    position: [2, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 341650,
    names: {
      en: "Emeni's Ambulatory Flesh",
      cn: "艾米妮的可行动躯体",
      fr: "Chair ambulante d’Éméni",
      ru: "Временная плоть Эмени",
    },
    icon: "inv_helm_crown_c_01_rose.jpg",
    soulbind: "Emeni",
    position: [2, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 6000839217,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Emeni",
    position: [3, 1],
    renown: 7,
    active: false,
    stat_bonus: {},
  },
  {
    id: 324440,
    names: {
      en: "Cartilaginous Legs",
      cn: "柔韧腿部",
      fr: "Jambes cartilagineuses",
      ru: "Хрящевые ноги",
    },
    icon: "inv_pants_leather_raiddruid_j_01.jpg",
    soulbind: "Emeni",
    position: [4, 0],
    renown: 13,
    active: false,
    stat_bonus: {},
  },
  {
    id: 324441,
    names: {
      en: "Hearth Kidneystone",
      cn: "肾结炉石",
      fr: "Néphrite de foyer",
      ru: "Почечный камень возвращения",
    },
    icon: "item_alchemiststonec.jpg",
    soulbind: "Emeni",
    position: [4, 2],
    renown: 13,
    active: false,
    stat_bonus: {},
  },
  {
    id: 6000839218,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Emeni",
    position: [5, 1],
    renown: 18,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 6000839219,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Emeni",
    position: [6, 0],
    renown: 28,
    active: false,
    stat_bonus: {},
    type: "Potency Conduit",
    slotted_id: -1,
  },
  {
    id: 6000839220,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Emeni",
    position: [6, 1],
    renown: 28,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 6000839221,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Emeni",
    position: [6, 2],
    renown: 28,
    active: false,
    stat_bonus: {},
  },
  {
    id: 323918,
    names: {
      en: "Gristled Toes",
      cn: "软骨脚趾",
      fr: "Orteils calcifiés",
      ru: "Загрубевшие ступни",
    },
    icon: "spell_nzinsanity_leadenfoot.jpg",
    soulbind: "Emeni",
    position: [7, 0],
    renown: 34,
    active: false,
    stat_bonus: {},
  },
  {
    id: 323919,
    names: {
      en: "Gnashing Chompers",
      cn: "啮咬咀嚼者",
      fr: "Ratiches grinçantes",
      ru: "Скрежещущие зубы",
    },
    icon: "ability_creature_poison_01.jpg",
    soulbind: "Emeni",
    position: [7, 1],
    renown: 34,
    active: false,
    stat_bonus: {},
  },
  {
    id: 323916,
    names: {
      en: "Sulfuric Emission",
      cn: "硫磺喷发",
      fr: "Émission sulfurique",
      ru: "Серный выброс",
    },
    icon: "spell_shadow_plaguecloud.jpg",
    soulbind: "Emeni",
    position: [7, 2],
    renown: 34,
    active: false,
    stat_bonus: {},
  },

  {
    id: 326514,
    names: {
      en: "Forgeborne Reveries",
      cn: "炉脉幻想",
      fr: "Rêveries forge-nées",
      ru: "Откровения мастера кузни",
    },
    icon: "garrison_greenarmor.jpg",
    soulbind: "Heirmir",
    position: [0, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 6000839231,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Heirmir",
    position: [1, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Potency Conduit",
    slotted_id: -1,
  },
  {
    id: 6000839234,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Heirmir",
    position: [1, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 326507,
    names: {
      en: "Resourceful Fleshcrafting",
      cn: "累积的血肉铸造",
      fr: "Recomposition des chairs ingénieuse",
      ru: "Хитроумная резьба по плоти",
    },
    icon: "inv_cooking_80_brinyflesh.jpg",
    soulbind: "Heirmir",
    position: [2, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 326504,
    names: {
      en: "Serrated Spaulders",
      cn: "锯齿护肩",
      fr: "Spallières dentelées",
      ru: "Зазубренные наплечники",
    },
    icon: "inv_misc_sawblade_01.jpg",
    soulbind: "Heirmir",
    position: [2, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 6000839236,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Heirmir",
    position: [3, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 326512,
    names: {
      en: "Runeforged Spurs",
      cn: "符文熔铸之刺",
      fr: "Éperons runeforgés",
      ru: "Выкованные в кузне рун шпоры",
    },
    icon: "trade_archaeology_bones-of-transformation.jpg",
    soulbind: "Heirmir",
    position: [4, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 326513,
    names: {
      en: "Bonesmith's Satchel",
      cn: "骨匠的袋子",
      fr: "Sacoche de forge-os",
      ru: "Сумка костоплава",
    },
    icon: "inv_misc_coinbag14.jpg",
    soulbind: "Heirmir",
    position: [4, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 6000839237,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Heirmir",
    position: [5, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 6000839238,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Heirmir",
    position: [6, 0],
    renown: 29,
    active: false,
    stat_bonus: {},
    type: "Potency Conduit",
    slotted_id: -1,
  },
  {
    id: 6000839239,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Heirmir",
    position: [6, 1],
    renown: 29,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 6000839241,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Heirmir",
    position: [6, 2],
    renown: 29,
    active: false,
    stat_bonus: {},
  },
  {
    id: 326511,
    names: {
      en: "Heirmir's Arsenal: Gorestompers",
      cn: "海尔米尔的军械库：伤口践踏者",
      fr: "Arsenal d’Heirmir : croquenots sanglants",
      ru: "Арсенал Гейрмир: кровоступы",
    },
    icon: "inv_boots_raidshaman_i_01.jpg",
    soulbind: "Heirmir",
    position: [7, 0],
    renown: 31,
    active: false,
    stat_bonus: {},
  },
  {
    id: 326572,
    names: {
      en: "Heirmir's Arsenal: Marrowed Gemstone",
      cn: "海尔米尔的军械库：髓噬宝石",
      fr: "Arsenal d’Heirmir : gemme médullaire",
      ru: "Арсенал Гейрмир: оссеиновый самоцвет",
    },
    icon: "inv_misc_enchantedpearla.jpg",
    soulbind: "Heirmir",
    position: [7, 1],
    renown: 31,
    active: false,
    stat_bonus: {},
  },
  {
    id: 326509,
    names: {
      en: "Heirmir's Arsenal: Ravenous Pendant",
      cn: "海尔米尔的军械库：贪婪垂饰",
      fr: "Arsenal d’Heirmir : pendentif vorace",
      ru: "Арсенал Гейрмир: прожорливая подвеска",
    },
    icon: "spell_deathknight_empowerruneblade.jpg",
    soulbind: "Heirmir",
    position: [7, 2],
    renown: 31,
    active: false,
    stat_bonus: {},
  },

  // Night Fae
  // Niya

  {
    id: 322721,
    names: {
      en: "Grove Invigoration",
      cn: "林地复兴",
      fr: "Revigoration du bosquet",
      ru: "Оздоровление рощи",
    },
    icon: "ability_druid_manatree.jpg",
    soulbind: "Niya",
    position: [0, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 6000839242,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Niya",
    position: [1, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Potency Conduit",
    slotted_id: -1,
  },
  {
    id: 7000839211,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Niya",
    position: [1, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 342270,
    names: {
      en: "Run Without Tiring",
      cn: "不休不疲",
      fr: "Revigoration du bosquet",
      ru: "Неустанный бег",
    },
    icon: "ability_racial_runningwild.jpg",
    soulbind: "Niya",
    position: [2, 0],
    renown: 3,
    active: false,
    stat_bonus: {},
  },
  {
    id: 320658,
    names: {
      en: "Stay on the Move",
      cn: "保持移动",
      fr: "Mobilité",
      ru: "В движении",
    },
    icon: "inv_misc_foot_centaur.jpg",
    soulbind: "Niya",
    position: [2, 2],
    renown: 3,
    active: false,
    stat_bonus: {},
  },
  {
    id: 7000839212,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Niya",
    position: [3, 1],
    renown: 7,
    active: false,
    stat_bonus: {},
  },
  {
    id: 320668,
    names: {
      en: "Nature's Splendor",
      cn: "自然的壮美",
      fr: "Splendeur de la nature",
      ru: "Великолепие природы",
    },
    icon: "inv_misc_bag_27.jpg",
    soulbind: "Niya",
    position: [4, 0],
    renown: 10,
    active: false,
    stat_bonus: {},
  },
  {
    id: 320687,
    names: {
      en: "Swift Patrol",
      cn: "快速巡逻",
      fr: "Patrouille véloce",
      ru: "Быстрое патрулирование",
    },
    icon: "ability_druid_supriseattack.jpg",
    soulbind: "Niya",
    position: [4, 2],
    renown: 10,
    active: false,
    stat_bonus: {},
  },
  {
    id: 7000839213,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Niya",
    position: [5, 1],
    renown: 18,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 7000839214,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Niya",
    position: [6, 0],
    renown: 25,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 7000839215,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Niya",
    position: [6, 1],
    renown: 25,
    active: false,
    stat_bonus: {},
    type: "Potency Conduit",
    slotted_id: -1,
  },
  {
    id: 7000839216,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Niya",
    position: [6, 2],
    renown: 25,
    active: false,
    stat_bonus: {},
  },
  {
    id: 320659,
    names: {
      en: "Niya's Tools: Burrs",
      cn: "尼娅的工具：锉刀",
      fr: "Outils de Niya : bardanes",
      ru: "Инструменты Нии: колючая лоза",
    },
    icon: "ability_rogue_trip.jpg",
    soulbind: "Niya",
    position: [7, 0],
    renown: 30,
    active: false,
    stat_bonus: {},
  },
  {
    id: 320660,
    names: {
      en: "Niya's Tools: Poison",
      cn: "尼娅的工具：毒药",
      fr: "Outils de Niya : poison",
      ru: "Инструменты Нии: яд",
    },
    icon: "trade_brewpoison.jpg",
    soulbind: "Niya",
    position: [7, 1],
    renown: 30,
    active: false,
    stat_bonus: {},
  },
  {
    id: 320662,
    names: {
      en: "Niya's Tools: Herbs",
      cn: "尼娅的工具：草药",
      fr: "Outils de Niya : plantes",
      ru: "Инструменты Нии: травы",
    },
    icon: "inv_misc_herb_arthastear_petal.jpg",
    soulbind: "Niya",
    position: [7, 2],
    renown: 30,
    active: false,
    stat_bonus: {},
  },
  // Dreamweaver
  {
    id: 319217,
    names: {
      en: "Podtender",
      cn: "灵茧守护者",
      fr: "Cocon curatif",
      ru: "Защитный стручок",
    },
    icon: "inv_farm_herbseed.jpg",
    soulbind: "Dreamweaver",
    position: [0, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 908123,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Dreamweaver",
    position: [1, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 7189321,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Dreamweaver",
    position: [1, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 89123123,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Dreamweaver",
    position: [2, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Potency Conduit",
    slotted_id: -1,
    type: "Potency Conduit",
    slotted_id: -1,
  },
  {
    id: 319211,
    names: {
      en: "Soothing Voice",
      cn: "延缓之声",
      fr: "Voix apaisante",
      ru: "Успокаивающий голос",
    },
    icon: "spell_nature_sleep.jpg",
    soulbind: "Dreamweaver",
    position: [3, 0],
    renown: 9,
    active: false,
    stat_bonus: {},
  },
  {
    id: 319210,
    names: {
      en: "Social Butterfly",
      cn: "蝴蝶效应",
      fr: "Papillonnage",
      ru: "Украшение компании",
    },
    icon: "spell_shaman_blessingofeternals.jpg",
    soulbind: "Dreamweaver",
    position: [3, 1],
    renown: 9,
    active: false,
    stat_bonus: {},
  },
  {
    id: 319213,
    names: {
      en: "Empowered Chrysalis",
      cn: "灵茧之力",
      fr: "Chrysalide renforcée",
      ru: "Усиленная хризалида",
    },
    icon: "ability_druid_dreamstate.jpg",
    soulbind: "Dreamweaver",
    position: [3, 2],
    renown: 9,
    active: false,
    stat_bonus: {},
  },
  {
    id: 98321789,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Dreamweaver",
    position: [4, 0],
    renown: 13,
    active: false,
    stat_bonus: {},
    type: "Potency Conduit",
    slotted_id: -1,
  },
  {
    id: 890213,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Dreamweaver",
    position: [4, 1],
    renown: 13,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 9321678,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Dreamweaver",
    position: [4, 2],
    renown: 13,
    active: false,
    stat_bonus: {},
  },
  {
    id: 732891,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Dreamweaver",
    position: [5, 1],
    renown: 21,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 319214,
    names: {
      en: "Faerie Dust",
      cn: "妖精之尘",
      fr: "Poussière de fée",
      ru: "Волшебная пыльца",
    },
    icon: "inv_misc_dust.jpg",
    soulbind: "Dreamweaver",
    position: [6, 0],
    renown: 29,
    active: false,
    stat_bonus: {},
  },
  {
    id: 319216,
    names: {
      en: "Somnambulist",
      cn: "梦游者",
      fr: "Somnambule",
      ru: "Сомнамбула",
    },
    icon: "ability_xavius_dreamsimulacrum.jpg",
    soulbind: "Dreamweaver",
    position: [6, 2],
    renown: 29,
    active: false,
    stat_bonus: {},
  },
  {
    id: 319191,
    names: {
      en: "Field of Blossoms",
      cn: "繁华原野",
      fr: "Champ de fleurs",
      ru: "Цветочное поле",
    },
    icon: "inv_misc_trailofflowers.jpg",
    soulbind: "Dreamweaver",
    position: [7, 1],
    renown: 34,
    active: false,
    stat_bonus: {},
  },

  // Korayn

  {
    id: 325066,
    names: {
      en: "Wild Hunt Tactics",
      cn: "荒猎团战术",
      fr: "Tactiques de l’Hallali",
      ru: "Тактика Дикой Охоты",
    },
    icon: "ability_blackhand_marked4death.jpg",
    soulbind: "Korayn",
    position: [0, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 8000839211,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Korayn",
    position: [1, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Potency Conduit",
    slotted_id: -1,
  },
  {
    id: 58971321,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Korayn",
    position: [1, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 325067,
    names: {
      en: "Horn of the Wild Hunt",
      cn: "荒猎号角",
      fr: "Cor de l’Hallali",
      ru: "Рог Дикой Охоты",
    },
    icon: "inv_misc_monsterhorn_05.jpg",
    soulbind: "Korayn",
    position: [2, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 325065,
    names: {
      en: "Wild Hunt's Charge",
      cn: "荒猎冲锋",
      fr: "Charge de l’Hallali",
      ru: "Рывок Дикой Охоты",
    },
    icon: "ability_druid_dash.jpg",
    soulbind: "Korayn",
    position: [2, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 8000839212,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Korayn",
    position: [3, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 325072,
    names: {
      en: "Vorkai Sharpening Techniques",
      cn: "沃卡伊打磨技术",
      fr: "Techniques d’aiguisage vorkaï",
      ru: "Воркайская заточка клинков",
    },
    icon: "inv_polearm_2h_heirloomspear_c_01.jpg",
    soulbind: "Korayn",
    position: [4, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 325073,
    names: {
      en: "Get In Formation",
      cn: "列入阵型",
      fr: "En formation",
      ru: "Встать в строй",
    },
    icon: "inv_misc_foot_centaur.jpg",
    soulbind: "Korayn",
    position: [4, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 8979321,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Korayn",
    position: [5, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 71893216,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Korayn",
    position: [6, 0],
    renown: 28,
    active: false,
    stat_bonus: {},
    type: "Potency Conduit",
    slotted_id: -1,
  },
  {
    id: 6783212,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Korayn",
    position: [6, 1],
    renown: 28,
    active: false,
    stat_bonus: {},
    type: "Endurance Conduit",
    slotted_id: -1,
  },
  {
    id: 8000839213,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Korayn",
    position: [6, 2],
    renown: 28,
    active: false,
    stat_bonus: {},
  },
  {
    id: 325068,
    names: {
      en: "Face Your Foes",
      cn: "勇面敌人",
      fr: "Face au danger",
      ru: "Лицом к лицу с врагами",
    },
    icon: "ability_warrior_endlessrage.jpg",
    soulbind: "Korayn",
    position: [7, 0],
    renown: 31,
    active: false,
    stat_bonus: {},
  },
  {
    id: 325069,
    names: {
      en: "First Strike",
      cn: "争先打击",
      fr: "Frappe initiale",
      ru: "Первый удар",
    },
    icon: "ability_rogue_surpriseattack.jpg",
    soulbind: "Korayn",
    position: [7, 1],
    renown: 31,
    active: false,
    stat_bonus: {},
  },
  {
    id: 325601,
    names: {
      en: "Hold the Line",
      cn: "坚守阵地",
      fr: "Tenir le front",
      ru: "Дисциплина защитника",
    },
    icon: "spell_nature_shamanrage.jpg",
    soulbind: "Korayn",
    position: [7, 2],
    renown: 31,
    active: false,
    stat_bonus: {},
  },

  // Venthyr
  // Nadjia

  {
    id: 331586,
    names: {
      en: "Thrill Seeker",
      cn: "兴奋追猎者",
      fr: "Sensations fortes",
      ru: "Поиск острых ощущений",
    },
    icon: "ability_rogue_bloodsplatter.jpg",
    soulbind: "Nadjia",
    position: [0, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 8000839214,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Nadjia",
    position: [1, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 8000839215,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Nadjia",
    position: [1, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 331576,
    names: {
      en: "Agent of Chaos",
      cn: "混沌代理人",
      fr: "Agent du chaos",
      ru: "Агент хаоса",
    },
    icon: "spell_shadow_deathsembrace.jpg",
    soulbind: "Nadjia",
    position: [2, 0],
    renown: 3,
    active: false,
    stat_bonus: {},
  },
  {
    id: 331577,
    names: {
      en: "Fancy Footwork",
      cn: "眩步皮靴",
      fr: "Joli jeu de jambes",
      ru: "Мастерская работа ног",
    },
    icon: "ability_rogue_sprint_blue.jpg",
    soulbind: "Nadjia",
    position: [2, 2],
    renown: 3,
    active: false,
    stat_bonus: {},
  },
  {
    id: 8000839216,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Nadjia",
    position: [3, 1],
    renown: 7,
    active: false,
    stat_bonus: {},
  },
  {
    id: 331579,
    names: {
      en: "Friends in Low Places",
      cn: "患难之友",
      fr: "Amis des bas-fonds",
      ru: "Полезные друзья",
    },
    icon: "ability_rogue_dirtydeeds.jpg",
    soulbind: "Nadjia",
    position: [4, 1],
    renown: 10,
    active: false,
    stat_bonus: {},
  },
  {
    id: 8000839217,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Nadjia",
    position: [5, 1],
    renown: 21,
    active: false,
    stat_bonus: {},
  },
  {
    id: 8000839218,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Nadjia",
    position: [6, 0],
    renown: 25,
    active: false,
    stat_bonus: {},
  },
  {
    id: 8000839219,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Nadjia",
    position: [6, 1],
    renown: 25,
    active: false,
    stat_bonus: {},
  },
  {
    id: 8000839221,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Nadjia",
    position: [6, 2],
    renown: 25,
    active: false,
    stat_bonus: {},
  },
  {
    id: 331582,
    names: {
      en: "Familiar Predicaments",
      cn: "漠然困境",
      fr: "Embarras habituels",
      ru: "Знакомые затруднения",
    },
    icon: "sha_ability_rogue_bloodyeye_nightmare.jpg",
    soulbind: "Nadjia",
    position: [7, 0],
    renown: 30,
    active: false,
    stat_bonus: {},
  },
  {
    id: 331580,
    names: {
      en: "Exacting Preparation",
      cn: "精心准备",
      fr: "Mise au point des préparatifs",
      ru: "Тщательная подготовка",
    },
    icon: "trade_brewpoison.jpg",
    soulbind: "Nadjia",
    position: [7, 1],
    renown: 30,
    active: false,
    stat_bonus: {},
  },
  {
    id: 331584,
    names: {
      en: "Dauntless Duelist",
      cn: "无畏决斗者",
      fr: "Duelliste déterminé",
      ru: "Бесстрашный дуэлянт",
    },
    icon: "inv_tabard_duelersguild.jpg",
    soulbind: "Nadjia",
    position: [7, 2],
    renown: 30,
    active: false,
    stat_bonus: {},
  },

  // Theotar
  {
    id: 336239,
    names: {
      en: "Soothing Shade",
      cn: "抚慰阴影",
      fr: "Ombre apaisante",
      ru: "Успокаивающая тень",
    },
    icon: "archaeology_5_0_umbrellaofchiji.jpg",
    soulbind: "Theotar",
    position: [0, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 8000839222,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Theotar",
    position: [1, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 8000839223,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Theotar",
    position: [1, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 336140,
    names: {
      en: "Watch the Shoes!",
      cn: "看好脚下！",
      fr: "Ne marchez pas n’importe où !",
      ru: "Смотри под ноги!",
    },
    icon: "inv_raidpriestmythic_q_01boot.jpg",
    soulbind: "Theotar",
    position: [2, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 336147,
    names: {
      en: "Leisurely Gait",
      cn: "从容不迫",
      fr: "Démarche nonchalante",
      ru: "Неспешная походка",
    },
    icon: "spell_lifegivingspeed.jpg",
    soulbind: "Theotar",
    position: [2, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 8000839224,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Theotar",
    position: [3, 1],
    renown: 9,
    active: false,
    stat_bonus: {},
  },
  {
    id: 336247,
    names: {
      en: "Life of the Party",
      cn: "聚会生活",
      fr: "Boute-en-train",
      ru: "Душа компании",
    },
    icon: "achievement_halloween_smiley_01.jpg",
    soulbind: "Theotar",
    position: [4, 0],
    renown: 13,
    active: false,
    stat_bonus: {},
  },
  {
    id: 336184,
    names: {
      en: "Exquisite Ingredients",
      cn: "精致的材料",
      fr: "Ingrédients exquis",
      ru: "Изысканные ингредиенты",
    },
    icon: "achievement_guildperk_bountifulbags.jpg",
    soulbind: "Theotar",
    position: [4, 2],
    renown: 13,
    active: false,
    stat_bonus: {},
  },
  {
    id: 8000839225,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Theotar",
    position: [5, 1],
    renown: 18,
    active: false,
    stat_bonus: {},
  },
  {
    id: 8000839226,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Theotar",
    position: [6, 0],
    renown: 28,
    active: false,
    stat_bonus: {},
  },
  {
    id: 8000839227,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Theotar",
    position: [6, 1],
    renown: 28,
    active: false,
    stat_bonus: {},
  },
  {
    id: 8000839228,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Theotar",
    position: [6, 2],
    renown: 28,
    active: false,
    stat_bonus: {},
  },
  {
    id: 336245,
    names: {
      en: "Token of Appreciation",
      cn: "感激之情",
      fr: "Preuve d’estime",
      ru: "Знак признательности",
    },
    icon: "inv_misc_coin_01.jpg",
    soulbind: "Theotar",
    position: [7, 0],
    renown: 34,
    active: false,
    stat_bonus: {},
  },
  {
    id: 336243,
    names: {
      en: "Refined Palate",
      cn: "高雅味觉",
      fr: "Fin palais",
      ru: "Тонкий вкус",
    },
    icon: "inv_trinket_revendreth_01_gold.jpg",
    soulbind: "Theotar",
    position: [7, 1],
    renown: 34,
    active: false,
    stat_bonus: {},
  },
  {
    id: 319983,
    names: {
      en: "Wasteland Propriety",
      cn: "废土礼节",
      fr: "Convenances du désert",
      ru: "Этикет пустошей",
    },
    icon: "inv_drink_23.jpg",
    soulbind: "Theotar",
    position: [7, 2],
    renown: 34,
    active: false,
    stat_bonus: {},
  },

  // Draven
  {
    id: 340159,
    names: {
      en: "Service In Stone",
      cn: "岩石效命",
      fr: "Pierre de service",
      ru: "Каменное служение",
    },
    icon: "inv_misc_reforgedarchstone_01.jpg",
    soulbind: "Draven",
    position: [0, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 9000839211,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Draven",
    position: [1, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 9000839212,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Draven",
    position: [1, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 319982,
    names: {
      en: "Move As One",
      cn: "行动一致",
      fr: "Face au danger",
      ru: "Строевой шаг",
    },
    icon: "spell_holy_prayerofhealing.jpg",
    soulbind: "Draven",
    position: [2, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 319978,
    names: {
      en: "Enduring Gloom",
      cn: "持续阴霾",
      fr: "Obscurité persistante",
      ru: "Стойкий мрак",
    },
    icon: "ability_garrosh_touch_of_yshaarj.jpg",
    soulbind: "Draven",
    position: [2, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 9000839213,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Draven",
    position: [3, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 332755,
    names: {
      en: "Unbreakable Body",
      cn: "无摧身躯",
      fr: "Corps indestructible",
      ru: "Несокрушимое тело",
    },
    icon: "inv_chest_mail_revendreth_d_01.jpg",
    soulbind: "Draven",
    position: [4, 0],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 332756,
    names: {
      en: "Expedition Leader",
      cn: "远征队领袖",
      fr: "Chef d’expédition",
      ru: "Руководитель экспедиции",
    },
    icon: "spell_misc_warsongfocus.jpg",
    soulbind: "Draven",
    position: [4, 2],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 9000839214,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Draven",
    position: [5, 1],
    renown: 0,
    active: false,
    stat_bonus: {},
  },
  {
    id: 9000839215,
    names: {
      en: "Potency Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Draven",
    position: [6, 0],
    renown: 29,
    active: false,
    stat_bonus: {},
  },
  {
    id: 9000839216,
    names: {
      en: "Endurance Conduit",
      cn: "",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Draven",
    position: [6, 1],
    renown: 29,
    active: false,
    stat_bonus: {},
  },
  {
    id: 9000839217,
    names: {
      en: "Finesse Conduit",
      cn: "耐心之瓶",
    },
    icon: "EmptyConduit.jpg",
    soulbind: "Draven",
    position: [6, 2],
    renown: 29,
    active: false,
    stat_bonus: {},
  },
  {
    id: 332754,
    names: {
      en: "Hold Your Ground",
      cn: "坚守阵地",
      fr: "Inflexible",
      ru: "Ни шагу назад",
    },
    icon: "achievement_bg_killxenemies_generalsroom.jpg",
    soulbind: "Draven",
    position: [7, 0],
    renown: 31,
    active: false,
    stat_bonus: {},
  },
  {
    id: 332753,
    names: {
      en: "Superior Tactics",
      cn: "高级战术",
      fr: "Supériorité tactique",
      ru: "Превосходство в тактике",
    },
    icon: "inv_inscription_80_warscroll_battleshout.jpg",
    soulbind: "Draven",
    position: [7, 1],
    renown: 31,
    active: false,
    stat_bonus: {},
  },
  {
    id: 319973,
    names: {
      en: "Built for War",
      cn: "为战而生",
      fr: "Conçu pour la guerre",
      ru: "Дитя войны",
    },
    icon: "ability_warrior_intensifyrage.jpg",
    soulbind: "Draven",
    position: [7, 2],
    renown: 31,
    active: false,
    stat_bonus: {},
  },
];

export const soulbindConnectors = [
  /*
    Angles:
    - Straight Line: 0
    - Standard Diagonal: 45 -> left, 315 -> right
    - Tight Diagonal: 55 -> left, 305 -> right
  */
  {
    soulbind: "Pelagos",
    src: "Vertical.PNG",
    position: [298, 10],
    angle: 0,
  },
  {
    soulbind: "Pelagos",
    src: "DiagonalShort.png",
    position: [287, 35],
    angle: 45,
  },
  {
    soulbind: "Pelagos",
    src: "DiagonalShort.png",
    position: [305, 35],
    angle: 315,
  },
  {
    soulbind: "Pelagos",
    src: "Vertical.PNG",
    position: [208, 100],
    angle: 0,
  },
  {
    soulbind: "Pelagos",
    src: "Vertical.PNG",
    position: [298, 85],
    angle: 0,
  },
  {
    soulbind: "Pelagos",
    src: "Vertical.PNG",
    position: [388, 100],
    angle: 0,
  },
  {
    soulbind: "Pelagos",
    src: "DiagonalShort.png",
    position: [202, 198],
    angle: 305,
  },
  {
    soulbind: "Pelagos",
    src: "Vertical.PNG",
    position: [298, 165],
    angle: 0,
  },
  {
    soulbind: "Pelagos",
    src: "DiagonalShort.png",
    position: [400, 198],
    angle: 55,
  },
  {
    soulbind: "Pelagos",
    src: "DiagonalShort.png",
    position: [294, 275],
    angle: 45,
  },
  {
    soulbind: "Pelagos",
    src: "DiagonalShort.png",
    position: [304, 275],
    angle: 315,
  },
  {
    soulbind: "Pelagos",
    src: "DiagonalShort.png",
    position: [215, 377],
    angle: 315,
  },
  {
    soulbind: "Pelagos",
    src: "DiagonalShort.png",
    position: [380, 377],
    angle: 45,
  },
  {
    soulbind: "Pelagos",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 55,
  },
  {
    soulbind: "Pelagos",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 305,
  },
  {
    soulbind: "Pelagos",
    src: "DiagonalShort.png",
    position: [216, 533],
    angle: 315,
  },
  {
    soulbind: "Pelagos",
    src: "DiagonalShort.png",
    position: [380, 533],
    angle: 45,
  },

  // Kleia
  {
    soulbind: "Kleia",
    src: "DiagonalShort.png",
    position: [287, 35],
    angle: 45,
  },
  {
    soulbind: "Kleia",
    src: "DiagonalShort.png",
    position: [305, 35],
    angle: 315,
  },
  {
    soulbind: "Kleia",
    src: "Vertical.PNG",
    position: [208, 100],
    angle: 0,
  },
  {
    soulbind: "Kleia",
    src: "Vertical.PNG",
    position: [388, 100],
    angle: 0,
  },
  {
    soulbind: "Kleia",
    src: "DiagonalShort.png",
    position: [202, 198],
    angle: 305,
  },
  {
    soulbind: "Kleia",
    src: "DiagonalShort.png",
    position: [400, 198],
    angle: 55,
  },
  {
    soulbind: "Kleia",
    src: "DiagonalShort.png",
    position: [294, 275],
    angle: 45,
  },
  {
    soulbind: "Kleia",
    src: "DiagonalShort.png",
    position: [304, 275],
    angle: 315,
  },
  {
    soulbind: "Kleia",
    src: "DiagonalShort.png",
    position: [215, 377],
    angle: 315,
  },
  {
    soulbind: "Kleia",
    src: "DiagonalShort.png",
    position: [380, 377],
    angle: 45,
  },
  {
    soulbind: "Kleia",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 55,
  },
  {
    soulbind: "Kleia",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 305,
  },
  {
    soulbind: "Kleia",
    src: "Vertical.PNG",
    position: [298, 435],
    angle: 0,
  },
  {
    soulbind: "Kleia",
    src: "Vertical.PNG",
    position: [298, 510],
    angle: 0,
  },
  {
    soulbind: "Kleia",
    src: "Vertical.PNG",
    position: [208, 494],
    angle: 0,
  },
  {
    soulbind: "Kleia",
    src: "Vertical.PNG",
    position: [388, 494],
    angle: 0,
  },

  // Mikanikos
  {
    soulbind: "Mikanikos",
    src: "DiagonalShort.png",
    position: [287, 35],
    angle: 45,
  },
  {
    soulbind: "Mikanikos",
    src: "DiagonalShort.png",
    position: [305, 35],
    angle: 315,
  },
  {
    soulbind: "Mikanikos",
    src: "Vertical.PNG",
    position: [208, 100],
    angle: 0,
  },
  {
    soulbind: "Mikanikos",
    src: "Vertical.PNG",
    position: [388, 100],
    angle: 0,
  },
  {
    soulbind: "Mikanikos",
    src: "DiagonalShort.png",
    position: [202, 198],
    angle: 305,
  },

  {
    soulbind: "Mikanikos",
    src: "DiagonalShort.png",
    position: [400, 198],
    angle: 55,
  },
  {
    soulbind: "Mikanikos",
    src: "DiagonalShort.png",
    position: [294, 275],
    angle: 45,
  },
  {
    soulbind: "Mikanikos",
    src: "DiagonalShort.png",
    position: [304, 275],
    angle: 315,
  },
  {
    soulbind: "Mikanikos",
    src: "DiagonalShort.png",
    position: [215, 377],
    angle: 315,
  },
  {
    soulbind: "Mikanikos",
    src: "DiagonalShort.png",
    position: [380, 377],
    angle: 45,
  },
  {
    soulbind: "Mikanikos",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 55,
  },
  {
    soulbind: "Mikanikos",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 305,
  },
  {
    soulbind: "Mikanikos",
    src: "Vertical.PNG",
    position: [298, 435],
    angle: 0,
  },
  {
    soulbind: "Mikanikos",
    src: "Vertical.PNG",
    position: [298, 510],
    angle: 0,
  },
  {
    soulbind: "Mikanikos",
    src: "Vertical.PNG",
    position: [208, 494],
    angle: 0,
  },
  {
    soulbind: "Mikanikos",
    src: "Vertical.PNG",
    position: [388, 494],
    angle: 0,
  },

  // Niya
  {
    soulbind: "Niya",
    src: "DiagonalShort.png",
    position: [287, 35],
    angle: 45,
  },
  {
    soulbind: "Niya",
    src: "DiagonalShort.png",
    position: [305, 35],
    angle: 315,
  },
  {
    soulbind: "Niya",
    src: "Vertical.PNG",
    position: [208, 100],
    angle: 0,
  },
  {
    soulbind: "Niya",
    src: "Vertical.PNG",
    position: [388, 100],
    angle: 0,
  },
  {
    soulbind: "Niya",
    src: "DiagonalShort.png",
    position: [202, 198],
    angle: 305,
  },

  {
    soulbind: "Niya",
    src: "DiagonalShort.png",
    position: [400, 198],
    angle: 55,
  },
  {
    soulbind: "Niya",
    src: "DiagonalShort.png",
    position: [294, 275],
    angle: 45,
  },
  {
    soulbind: "Niya",
    src: "DiagonalShort.png",
    position: [304, 275],
    angle: 315,
  },
  {
    soulbind: "Niya",
    src: "DiagonalShort.png",
    position: [215, 377],
    angle: 315,
  },
  {
    soulbind: "Niya",
    src: "DiagonalShort.png",
    position: [380, 377],
    angle: 45,
  },
  {
    soulbind: "Niya",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 55,
  },
  {
    soulbind: "Niya",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 305,
  },
  {
    soulbind: "Niya",
    src: "Vertical.PNG",
    position: [298, 435],
    angle: 0,
  },
  {
    soulbind: "Niya",
    src: "Vertical.PNG",
    position: [298, 510],
    angle: 0,
  },
  {
    soulbind: "Niya",
    src: "Vertical.PNG",
    position: [208, 494],
    angle: 0,
  },
  {
    soulbind: "Niya",
    src: "Vertical.PNG",
    position: [388, 494],
    angle: 0,
  },

  // Korayn
  {
    soulbind: "Korayn",
    src: "DiagonalShort.png",
    position: [287, 35],
    angle: 45,
  },
  {
    soulbind: "Korayn",
    src: "DiagonalShort.png",
    position: [305, 35],
    angle: 315,
  },
  {
    soulbind: "Korayn",
    src: "Vertical.PNG",
    position: [208, 100],
    angle: 0,
  },
  {
    soulbind: "Korayn",
    src: "Vertical.PNG",
    position: [388, 100],
    angle: 0,
  },
  {
    soulbind: "Korayn",
    src: "DiagonalShort.png",
    position: [202, 198],
    angle: 305,
  },

  {
    soulbind: "Korayn",
    src: "DiagonalShort.png",
    position: [400, 198],
    angle: 55,
  },
  {
    soulbind: "Korayn",
    src: "DiagonalShort.png",
    position: [294, 275],
    angle: 45,
  },
  {
    soulbind: "Korayn",
    src: "DiagonalShort.png",
    position: [304, 275],
    angle: 315,
  },
  {
    soulbind: "Korayn",
    src: "DiagonalShort.png",
    position: [215, 377],
    angle: 315,
  },
  {
    soulbind: "Korayn",
    src: "DiagonalShort.png",
    position: [380, 377],
    angle: 45,
  },
  {
    soulbind: "Korayn",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 55,
  },
  {
    soulbind: "Korayn",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 305,
  },
  {
    soulbind: "Korayn",
    src: "Vertical.PNG",
    position: [298, 435],
    angle: 0,
  },
  {
    soulbind: "Korayn",
    src: "Vertical.PNG",
    position: [298, 510],
    angle: 0,
  },
  {
    soulbind: "Korayn",
    src: "Vertical.PNG",
    position: [208, 494],
    angle: 0,
  },
  {
    soulbind: "Korayn",
    src: "Vertical.PNG",
    position: [388, 494],
    angle: 0,
  },

  // Theotar
  {
    soulbind: "Nadjia",
    src: "DiagonalShort.png",
    position: [287, 35],
    angle: 45,
  },
  {
    soulbind: "Nadjia",
    src: "DiagonalShort.png",
    position: [305, 35],
    angle: 315,
  },
  {
    soulbind: "Nadjia",
    src: "Vertical.PNG",
    position: [208, 100],
    angle: 0,
  },
  {
    soulbind: "Nadjia",
    src: "Vertical.PNG",
    position: [388, 100],
    angle: 0,
  },
  {
    soulbind: "Nadjia",
    src: "DiagonalShort.png",
    position: [202, 198],
    angle: 305,
  },

  {
    soulbind: "Nadjia",
    src: "DiagonalShort.png",
    position: [400, 198],
    angle: 55,
  },
  {
    soulbind: "Nadjia",
    src: "Vertical.PNG",
    position: [298, 250],
    angle: 0,
  },

  {
    soulbind: "Nadjia",
    src: "Vertical.PNG",
    position: [298, 350],
    angle: 0,
  },

  {
    soulbind: "Nadjia",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 55,
  },
  {
    soulbind: "Nadjia",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 305,
  },
  {
    soulbind: "Nadjia",
    src: "Vertical.PNG",
    position: [298, 435],
    angle: 0,
  },
  {
    soulbind: "Nadjia",
    src: "Vertical.PNG",
    position: [298, 510],
    angle: 0,
  },
  {
    soulbind: "Nadjia",
    src: "Vertical.PNG",
    position: [208, 494],
    angle: 0,
  },
  {
    soulbind: "Nadjia",
    src: "Vertical.PNG",
    position: [388, 494],
    angle: 0,
  },

  // Theotar
  {
    soulbind: "Theotar",
    src: "DiagonalShort.png",
    position: [287, 35],
    angle: 45,
  },
  {
    soulbind: "Theotar",
    src: "DiagonalShort.png",
    position: [305, 35],
    angle: 315,
  },
  {
    soulbind: "Theotar",
    src: "Vertical.PNG",
    position: [208, 100],
    angle: 0,
  },
  {
    soulbind: "Theotar",
    src: "Vertical.PNG",
    position: [388, 100],
    angle: 0,
  },
  {
    soulbind: "Theotar",
    src: "DiagonalShort.png",
    position: [202, 198],
    angle: 305,
  },

  {
    soulbind: "Theotar",
    src: "DiagonalShort.png",
    position: [400, 198],
    angle: 55,
  },
  {
    soulbind: "Theotar",
    src: "DiagonalShort.png",
    position: [294, 275],
    angle: 45,
  },
  {
    soulbind: "Theotar",
    src: "DiagonalShort.png",
    position: [304, 275],
    angle: 315,
  },
  {
    soulbind: "Theotar",
    src: "DiagonalShort.png",
    position: [215, 377],
    angle: 315,
  },
  {
    soulbind: "Theotar",
    src: "DiagonalShort.png",
    position: [380, 377],
    angle: 45,
  },
  {
    soulbind: "Theotar",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 55,
  },
  {
    soulbind: "Theotar",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 305,
  },
  {
    soulbind: "Theotar",
    src: "Vertical.PNG",
    position: [298, 435],
    angle: 0,
  },
  {
    soulbind: "Theotar",
    src: "Vertical.PNG",
    position: [298, 510],
    angle: 0,
  },
  {
    soulbind: "Theotar",
    src: "Vertical.PNG",
    position: [208, 494],
    angle: 0,
  },
  {
    soulbind: "Theotar",
    src: "Vertical.PNG",
    position: [388, 494],
    angle: 0,
  },

  // Draven
  {
    soulbind: "Draven",
    src: "DiagonalShort.png",
    position: [287, 35],
    angle: 45,
  },
  {
    soulbind: "Draven",
    src: "DiagonalShort.png",
    position: [305, 35],
    angle: 315,
  },
  {
    soulbind: "Draven",
    src: "Vertical.PNG",
    position: [208, 100],
    angle: 0,
  },
  {
    soulbind: "Draven",
    src: "Vertical.PNG",
    position: [388, 100],
    angle: 0,
  },
  {
    soulbind: "Draven",
    src: "DiagonalShort.png",
    position: [202, 198],
    angle: 305,
  },

  {
    soulbind: "Draven",
    src: "DiagonalShort.png",
    position: [400, 198],
    angle: 55,
  },
  {
    soulbind: "Draven",
    src: "DiagonalShort.png",
    position: [294, 275],
    angle: 45,
  },
  {
    soulbind: "Draven",
    src: "DiagonalShort.png",
    position: [304, 275],
    angle: 315,
  },
  {
    soulbind: "Draven",
    src: "DiagonalShort.png",
    position: [215, 377],
    angle: 315,
  },
  {
    soulbind: "Draven",
    src: "DiagonalShort.png",
    position: [380, 377],
    angle: 45,
  },
  {
    soulbind: "Draven",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 55,
  },
  {
    soulbind: "Draven",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 305,
  },
  {
    soulbind: "Draven",
    src: "Vertical.PNG",
    position: [298, 435],
    angle: 0,
  },
  {
    soulbind: "Draven",
    src: "Vertical.PNG",
    position: [298, 510],
    angle: 0,
  },
  {
    soulbind: "Draven",
    src: "Vertical.PNG",
    position: [208, 494],
    angle: 0,
  },
  {
    soulbind: "Draven",
    src: "Vertical.PNG",
    position: [388, 494],
    angle: 0,
  },

  // Emeni
  {
    soulbind: "Emeni",
    src: "DiagonalShort.png",
    position: [287, 35],
    angle: 45,
  },
  {
    soulbind: "Emeni",
    src: "DiagonalShort.png",
    position: [305, 35],
    angle: 315,
  },
  {
    soulbind: "Emeni",
    src: "Vertical.PNG",
    position: [208, 100],
    angle: 0,
  },
  {
    soulbind: "Emeni",
    src: "Vertical.PNG",
    position: [388, 100],
    angle: 0,
  },
  {
    soulbind: "Emeni",
    src: "DiagonalShort.png",
    position: [202, 198],
    angle: 305,
  },

  {
    soulbind: "Emeni",
    src: "DiagonalShort.png",
    position: [400, 198],
    angle: 55,
  },
  {
    soulbind: "Emeni",
    src: "DiagonalShort.png",
    position: [294, 275],
    angle: 45,
  },
  {
    soulbind: "Emeni",
    src: "DiagonalShort.png",
    position: [304, 275],
    angle: 315,
  },
  {
    soulbind: "Emeni",
    src: "DiagonalShort.png",
    position: [215, 377],
    angle: 315,
  },
  {
    soulbind: "Emeni",
    src: "DiagonalShort.png",
    position: [380, 377],
    angle: 45,
  },
  {
    soulbind: "Emeni",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 55,
  },
  {
    soulbind: "Emeni",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 305,
  },
  {
    soulbind: "Emeni",
    src: "Vertical.PNG",
    position: [298, 435],
    angle: 0,
  },
  {
    soulbind: "Emeni",
    src: "Vertical.PNG",
    position: [298, 510],
    angle: 0,
  },
  {
    soulbind: "Emeni",
    src: "Vertical.PNG",
    position: [208, 494],
    angle: 0,
  },
  {
    soulbind: "Emeni",
    src: "Vertical.PNG",
    position: [388, 494],
    angle: 0,
  },

  // Emeni
  {
    soulbind: "Heirmir",
    src: "DiagonalShort.png",
    position: [287, 35],
    angle: 45,
  },
  {
    soulbind: "Heirmir",
    src: "DiagonalShort.png",
    position: [305, 35],
    angle: 315,
  },
  {
    soulbind: "Heirmir",
    src: "Vertical.PNG",
    position: [208, 100],
    angle: 0,
  },
  {
    soulbind: "Heirmir",
    src: "Vertical.PNG",
    position: [388, 100],
    angle: 0,
  },
  {
    soulbind: "Heirmir",
    src: "DiagonalShort.png",
    position: [202, 198],
    angle: 305,
  },

  {
    soulbind: "Heirmir",
    src: "DiagonalShort.png",
    position: [400, 198],
    angle: 55,
  },
  {
    soulbind: "Heirmir",
    src: "DiagonalShort.png",
    position: [294, 275],
    angle: 45,
  },
  {
    soulbind: "Heirmir",
    src: "DiagonalShort.png",
    position: [304, 275],
    angle: 315,
  },
  {
    soulbind: "Heirmir",
    src: "DiagonalShort.png",
    position: [215, 377],
    angle: 315,
  },
  {
    soulbind: "Heirmir",
    src: "DiagonalShort.png",
    position: [380, 377],
    angle: 45,
  },
  {
    soulbind: "Heirmir",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 55,
  },
  {
    soulbind: "Heirmir",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 305,
  },
  {
    soulbind: "Heirmir",
    src: "Vertical.PNG",
    position: [298, 435],
    angle: 0,
  },
  {
    soulbind: "Heirmir",
    src: "Vertical.PNG",
    position: [298, 510],
    angle: 0,
  },
  {
    soulbind: "Heirmir",
    src: "Vertical.PNG",
    position: [208, 494],
    angle: 0,
  },
  {
    soulbind: "Heirmir",
    src: "Vertical.PNG",
    position: [388, 494],
    angle: 0,
  },

  // Marileth
  {
    soulbind: "Marileth",
    src: "Vertical.PNG",
    position: [298, 10],
    angle: 0,
  },
  {
    soulbind: "Marileth",
    src: "DiagonalShort.png",
    position: [287, 35],
    angle: 45,
  },
  {
    soulbind: "Marileth",
    src: "DiagonalShort.png",
    position: [305, 35],
    angle: 315,
  },
  {
    soulbind: "Marileth",
    src: "Vertical.PNG",
    position: [208, 100],
    angle: 0,
  },
  {
    soulbind: "Marileth",
    src: "Vertical.PNG",
    position: [298, 85],
    angle: 0,
  },
  {
    soulbind: "Marileth",
    src: "Vertical.PNG",
    position: [388, 100],
    angle: 0,
  },
  {
    soulbind: "Marileth",
    src: "DiagonalShort.png",
    position: [202, 198],
    angle: 305,
  },
  {
    soulbind: "Marileth",
    src: "Vertical.PNG",
    position: [298, 165],
    angle: 0,
  },
  {
    soulbind: "Marileth",
    src: "DiagonalShort.png",
    position: [400, 198],
    angle: 55,
  },
  {
    soulbind: "Marileth",
    src: "DiagonalShort.png",
    position: [294, 275],
    angle: 45,
  },
  {
    soulbind: "Marileth",
    src: "DiagonalShort.png",
    position: [304, 275],
    angle: 315,
  },
  {
    soulbind: "Marileth",
    src: "DiagonalShort.png",
    position: [215, 377],
    angle: 315,
  },
  {
    soulbind: "Marileth",
    src: "DiagonalShort.png",
    position: [380, 377],
    angle: 45,
  },
  {
    soulbind: "Marileth",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 55,
  },
  {
    soulbind: "Marileth",
    src: "DiagonalShort.png",
    position: [298, 460],
    angle: 305,
  },
  {
    soulbind: "Marileth",
    src: "DiagonalShort.png",
    position: [216, 533],
    angle: 315,
  },
  {
    soulbind: "Marileth",
    src: "DiagonalShort.png",
    position: [380, 533],
    angle: 45,
  },

  // Dreamweaver
  {
    soulbind: "Dreamweaver",
    src: "DiagonalShort.png",
    position: [287, 35],
    angle: 45,
  },
  {
    soulbind: "Dreamweaver",
    src: "DiagonalShort.png",
    position: [305, 35],
    angle: 315,
  },
  {
    soulbind: "Dreamweaver",
    src: "DiagonalShort.png",
    position: [198, 122],
    angle: 305,
  },
  {
    soulbind: "Dreamweaver",
    src: "DiagonalShort.png",
    position: [400, 122],
    angle: 55,
  },
  {
    soulbind: "Dreamweaver",
    src: "DiagonalShort.png",
    position: [294, 198],
    angle: 45,
  },
  {
    soulbind: "Dreamweaver",
    src: "DiagonalShort.png",
    position: [304, 198],
    angle: 315,
  },
];
