
type GemEntry = {
  id: number; // The gems ID
  rarity: string; // Rarity level. We use this for settings deciding whether we should use Epic or Rare gems for example.
  name: string; // The English name for the gem.
  icon: string; // The icon to use for the gem.
  stats: { [key: string]: number };
  color: string;
}

export const classicGemDB: GemEntry[] = [
  // Mists of Pandaria Gems
    { // Sha-Touched
    id: 89882,
    rarity: "legendary",
    name: "Crystallized Horror",
    icon: "inv_legendary_breathofblackprince_str",
    stats: { intellect: 500 },
    color: "sha",
  },
    {
    id: 83150,
    rarity: "epic",
    name: "Brilliant Serpent's Eye",
    icon: "inv_jewelcrafting_dragonseye05",
    stats: { intellect: 320 },
    color: "red",
  },
  {
    id: 76694,
    rarity: "rare",
    name: "Brilliant Primordial Ruby",
    icon: "inv_misc_gem_x4_rare_cut_red",
    stats: { intellect: 160 },
    color: "red",
  },
  {
    id: 76628,
    rarity: "rare",
    name: "Perfect Brilliant Pandarian Garnet",
    icon: "inv_misc_gem_x4_uncommon_perfectcut_red",
    stats: { intellect: 160 },
    color: "red",
  },
    {
    id: 76562,
    rarity: "uncommon",
    name: "Brilliant Pandarian Garnet",
    icon: "inv_misc_gem_x4_uncommon_cut_red",
    stats: { intellect: 120 },
    color: "red",
  },
  {
    id: 76668,
    rarity: "rare",
    name: "Reckless Vermilion Onyx",
    icon: "inv_misc_gem_x4_rare_cut_orange",
    stats: { intellect: 80, haste: 160 },
    color: "orange", //"orange",
  },
  {
    id: 88943,
    rarity: "epic",
    name: "Reckless Sardonyx",
    icon: "inv_misc_gem_x4_uncommon_cut_orange",
    stats: { intellect: 100, haste: 200 },
    color: "orange", //"orange",
  },
  {
    id: 76602,
    rarity: "rare",
    name: "Perfect Reckless Tiger Opal",
    icon: "inv_misc_gem_x4_uncommon_perfectcut_orange",
    stats: { intellect: 80, haste: 160 },
    color: "orange", //"orange",
  },
  {
    id: 76536,
    rarity: "uncommon",
    name: "Reckless Tiger Opal",
    icon: "inv_misc_gem_x4_uncommon_cut_orange",
    stats: { intellect: 60, haste: 120 },
    color: "orange", //"orange",
  },
  {
    id: 76660,
    rarity: "rare",
    name: "Potent Vermilion Onyx",
    icon: "inv_misc_gem_x4_rare_cut_orange",
    stats: { intellect: 80, crit: 160 },
    color: "orange", //"orange",
  },
  {
    id: 76594,
    rarity: "rare",
    name: "Perfect Potent Tiger Opal",
    icon: "inv_misc_gem_x4_uncommon_perfectcut_orange",
    stats: { intellect: 80, crit: 160 },
    color: "orange", //"orange",
  },
  {
    id: 76528,
    rarity: "uncommon",
    name: "Potent Tiger Opal",
    icon: "inv_misc_gem_x4_uncommon_cut_orange",
    stats: { intellect: 60, crit: 120 },
    color: "orange", //"orange",
  },
  {
    id: 88942,
    rarity: "epic",
    name: "Potent Sardonyx",
    icon: "inv_misc_gem_x4_uncommon_cut_orange",
    stats: { intellect: 100, crit: 200 },
    color: "orange", //"orange",
  },
  {
    id: 76672,
    rarity: "rare",
    name: "Artful Vermilion Onyx",
    icon: "inv_misc_gem_x4_rare_cut_orange",
    stats: { intellect: 80, mastery: 160 },
    color: "orange", //"orange",
  },
  {
    id: 76606,
    rarity: "rare",
    name: "Perfect Artful Tiger Opal",
    icon: "inv_misc_gem_x4_uncommon_perfectcut_orange",
    stats: { intellect: 80, mastery: 160 },
    color: "orange", //"purple",
  },
  {
    id: 76540,
    rarity: "uncommon",
    name: "Perfect Artful Tiger Opal",
    icon: "inv_misc_gem_x4_uncommon_cut_orange",
    stats: { intellect: 60, mastery: 120 },
    color: "orange", //"purple",
  },
  {
    id: 88931,
    rarity: "epic",
    name: "Artful Sardonyx",
    icon: "inv_misc_gem_x4_uncommon_cut_orange",
    stats: { intellect: 100, mastery: 200 },
    color: "orange", //"purple",
  },
  {
    id: 76620,
    rarity: "rare",
    name: "Perfect Purified Roguestone",
    icon: "inv_misc_gem_x4_uncommon_perfectcut_purple",
    stats: { intellect: 80, spirit: 160 },
    color: "purple", //"purple",
  },
  {
    id: 76686,
    rarity: "rare",
    name: "Purified Imperial Amethyst",
    icon: "inv_misc_gem_x4_rare_cut_purple",
    stats: { intellect: 80, spirit: 160 },
    color: "purple", //"purple",
  },
  {
    id: 76554,
    rarity: "uncommon",
    name: "Purified Roguestone",
    icon: "inv_misc_gem_x4_uncommon_cut_purple",
    stats: { intellect: 60, spirit: 120 },
    color: "purple", //"purple",
  },
  {
    id: 88958,
    rarity: "epic",
    name: "Purified Zyanite",
    icon: "inv_misc_gem_x4_uncommon_cut_purple",
    stats: { intellect: 100, spirit: 200 },
    color: "purple", //"purple",
  },

  // Others
  {
    id: 76651,
    rarity: "rare",
    name: "Energized Wild Jade",
    icon: "inv_misc_gem_x4_rare_cut_green",
    stats: { haste: 160, spirit: 160 },
    color: "green", //"purple",
  },
  {
    id: 76585,
    rarity: "rare",
    name: "Perfect Energized Alexandrite",
    icon: "inv_misc_gem_x4_uncommon_perfectcut_green",
    stats: { haste: 160, spirit: 160 },
    color: "green", //"purple",
  },
  {
    id: 76640,
    rarity: "rare",
    name: "Misty Wild Jade",
    icon: "inv_misc_gem_x4_rare_cut_green",
    stats: { crit: 160, spirit: 160 },
    color: "green", //"purple",
  },
  {
    id: 76574,
    rarity: "rare",
    name: "Perfect Misty Alexandrite",
    icon: "inv_misc_gem_x4_uncommon_perfectcut_green",
    stats: { crit: 160, spirit: 160 },
    color: "green", //"purple",
  },
  {
    id: 76645,
    rarity: "rare",
    name: "Zen Wild Jade",
    icon: "inv_misc_gem_x4_rare_cut_green",
    stats: { mastery: 160, spirit: 160 },
    color: "green", //"purple",
  },
  {
    id: 76579,
    rarity: "rare",
    name: "Perfect Zen Alexandrite",
    icon: "inv_misc_gem_x4_rare_cut_green",
    stats: { mastery: 160, spirit: 160 },
    color: "green", //"purple",
  },

  // Pure Secondary Gems
  {
    id: 76699,
    rarity: "rare",
    name: "Quick Sun's Radiance",
    icon: "inv_misc_gem_x4_rare_cut_yellow",
    stats: { haste: 320 },
    color: "yellow", 
  },
  {
    id: 76633,
    rarity: "rare",
    name: "Perfect Quick Sunstone",
    icon: "inv_misc_gem_x4_rare_cut_yellow",
    stats: { haste: 320 },
    color: "yellow", 
  },
  {
    id: 83142,
    rarity: "epic",
    name: "Quick Serpent's Eye",
    icon: "inv_jewelcrafting_dragonseye03",
    stats: { haste: 480 },
    color: "yellow", 
  },
  {
    id: 76697,
    rarity: "rare",
    name: "Smooth Sun's Radiance",
    icon: "inv_misc_gem_x4_rare_cut_yellow",
    stats: { crit: 320 },
    color: "yellow", 
  },
    {
    id: 76631,
    rarity: "rare",
    name: "Perfect Smooth Sunstone",
    icon: "inv_misc_gem_x4_rare_cut_yellow",
    stats: { crit: 320 },
    color: "yellow", 
  },
  {
    id: 83146,
    rarity: "epic",
    name: "Smooth Serpent's Eye",
    icon: "inv_jewelcrafting_dragonseye03",
    stats: { crit: 480 },
    color: "yellow", 
  },
  {
    id: 76700,
    rarity: "rare",
    name: "Fractured Sun's Radiance",
    icon: "inv_misc_gem_x4_rare_cut_yellow",
    stats: { mastery: 320 },
    color: "yellow", 
  },
    {
    id: 76634,
    rarity: "rare",
    name: "Perfect Fractured Sunstone",
    icon: "inv_misc_gem_x4_rare_cut_yellow",
    stats: { mastery: 320 },
    color: "yellow", 
  },
  {
    id: 83143,
    rarity: "epic",
    name: "Fractured Serpent's Eye",
    icon: "inv_jewelcrafting_dragonseye03",
    stats: { mastery: 480 },
    color: "yellow", 
  },


  {
    id: 76885,
    rarity: "rare",
    name: "Burning Primal Diamond",
    icon: "inv_misc_gem_x4_metagem_cut",
    stats: { intellect: 160 },
    color: "meta",
  },
  {
    id: 95345,
    rarity: "legendary",
    name: "Courageous Primal Diamond",
    icon: "inv_legendary_chimeraoffear",
    stats: { intellect: 324 },
    color: "meta",
  },

  // cogwheels
  {
    id: 77541,
    rarity: "rare",
    name: "Smooth Tinker's Gear",
    icon: "inv_misc_enggizmos_30",
    stats: { crit: 600 },
    color: "cogwheel",
  },
  {
    id: 77542,
    rarity: "rare",
    name: "Quick Tinker's Gear",
    icon: "inv_misc_enggizmos_30",
    stats: { haste: 600 },
    color: "cogwheel",
  },
  {
    id: 77547,
    rarity: "rare",
    name: "Fractured Tinker's Gear",
    icon: "inv_misc_enggizmos_30",
    stats: { mastery: 600 },
    color: "cogwheel",
  },
  {
    id: 77546,
    rarity: "rare",
    name: "Fractured Tinker's Gear",
    icon: "inv_misc_enggizmos_30",
    stats: { spirit: 600 },
    color: "cogwheel",
  },

  // Cataclysm Gems
  /*
  {
    id: 71850,
    rarity: "epic",
    name: "Reckless Lava Coral",
    icon: "inv_misc_epicgem_04",
    stats: { intellect: 25, haste: 25 },
  },
  {
    id: 71868,
    rarity: "epic",
    name: "Purified Shadow Spinel",
    icon: "inv_misc_epicgem_05",
    stats: { intellect: 25, spirit: 25 },
  },
  {
    id: 71881,
    rarity: "epic",
    name: "Brilliant Queen's Garnet",
    icon: "inv_misc_epicgem_01",
    stats: { intellect: 50 },
  },
  {
    id: 59480,
    rarity: "epic",
    name: "Fractured Cogwheel",
    icon: "inv_misc_enggizmos_30",
    stats: { mastery: 208 },
  },
  {
    id: 59479,
    rarity: "epic",
    name: "Quick Cogwheel",
    icon: "inv_misc_enggizmos_30",
    stats: { haste: 208 },
  },
  {
    id: 59496,
    rarity: "epic",
    name: "Sparkling Cogwheel",
    icon: "inv_misc_enggizmos_30",
    stats: { spirit: 208 },
  },
  {
    id: 52236,
    rarity: "rare",
    name: "Purified Demonseye",
    icon: "inv_misc_cutgemsuperior3",
    stats: { intellect: 20, spirit: 20 },
  },
  {
    id: 52296,
    rarity: "rare",
    name: "Ember Shadowspirit Diamond",
    icon: "inv_misc_metagem_b",
    stats: { intellect: 54 },
  },
  {
    id: 52207,
    rarity: "rare",
    name: "Brilliant Inferno Ruby",
    icon: "inv_misc_cutgemsuperior6",
    stats: { intellect: 40 },
  },
  {
    id: 52208,
    rarity: "rare",
    name: "Reckless Ember Topaz",
    icon: "inv_misc_cutgemsuperior4",
    stats: { intellect: 20, haste: 20 },
  },*/
];
