export const externalsDB = [
  {
    guid: 47788,
    name: {
      en: "Guardian Spirit",
      de: "Schutzgeist",
      fr: "Esprit gardien",
      ru: "Оберегающий дух",
      ch: "守护之魂",
    },
    wowhead: "https://www.wowhead.com/spell=47788/guardian-spirit",
    icon: "spell_holy_guardianspirit",
    cooldown: 180,
  },

  {
    guid: 6940,
    name: {
      en: "Blessing of Sacrifice",
      de: "Segen der Aufopferung",
      fr: "Bénédiction de sacrifice",
      ru: "Жертвенное благословение",
      ch: "牺牲祝福",
    },
    wowhead: "https://www.wowhead.com/spell=6940/blessing-of-sacrifice",
    icon: "spell_holy_sealofsacrifice",
    cooldown: 120,
  },
  {
    guid: 1022,
    name: {
      en: "Blessing of Protection",
      de: "Segen des Schutzes",
      fr: "Bénédiction de protection",
      ru: "Благословение защиты",
      ch: "保护祝福",
    },
    wowhead: "https://www.wowhead.com/spell=1022/blessing-of-protection",
    icon: "spell_holy_sealofprotection",
    cooldown: 300,
  },
  {
    guid: 1044,
    name: {
      en: "Blessing of Freedom",
      de: "Segen der Freihei",
      fr: "Bénédiction de liberté",
      ru: "Благословенная свобода",
      ch: "自由祝福",
    },
    wowhead: "https://www.wowhead.com/spell=1044/blessing-of-freedom",
    icon: "spell_holy_sealofvalor",
    cooldown: 25,
  },
  {
    guid: 633,
    name: {
      en: "Lay on Hands",
      de: "Handauflegung",
      fr: "Imposition des mains",
      ru: "Возложение рук",
      ch: "圣疗术",
    },
    wowhead: "https://www.wowhead.com/spell=633/lay-on-hands",
    icon: "spell_holy_layonhands",
    cooldown: 600,
  },
  {
    guid: 102342,
    name: {
      en: "Ironbark",
      de: "Eisenborke",
      fr: "Ecorcefer",
      ru: "Железная кора",
      ch: "铁木树皮",
    },
    wowhead: "https://www.wowhead.com/spell=102342/ironbark",
    icon: "spell_druid_ironbark",
    cooldown: 90,
  },
  {
    guid: 29166,
    name: {
      en: "Innervate",
      de: "Anregen",
      fr: "Innervation",
      ru: "Озарение",
      ch: "激活",
    },
    wowhead: "https://www.wowhead.com/spell=29166/innervate",
    icon: "spell_nature_lightning",
    cooldown: 180,
  },

  {
    guid: 10060,
    name: {
      en: "Power Infusion",
      de: "Seele der Macht",
      fr: "Infusion de puissance",
      ru: "Придание сил",
      ch: "能量灌注",
    },
    wowhead: "https://www.wowhead.com/spell=10060/power-infusion",
    icon: "spell_holy_powerinfusion",
    cooldown: 120,
  },

  {
    guid: 116849,
    name: {
      en: "Life Cocoon",
      de: "Lebenskokon",
      fr: "Cocon de vie",
      ru: "Исцеляющий кокон",
      ch: "作茧缚命",
    },
    wowhead: "https://www.wowhead.com/spell=116849/life-cocoon",
    icon: "ability_monk_chicocoon",
    cooldown: 120,
  },

  {
    guid: 116841,
    name: {
      en: "Tiger's Lust",
      de: "Tigerrausch",
      fr: "Soif du tigre",
      ru: "Тигриное рвение",
      ch: "迅如猛虎",
    },
    wowhead: "https://www.wowhead.com/spell=116841/tigers-lust",
    icon: "ability_monk_tigerslust",
    cooldown: 30,
  },

  {
    guid: 33206,
    name: {
      en: "Pain Suppression",
      de: "Schmerzunterdrückung",
      fr: "Suppression de la douleur",
      ru: "Подавление боли",
      ch: "痛苦压制",
    },
    wowhead: "https://www.wowhead.com/spell=33206/pain-suppression",
    icon: "spell_holy_painsupression",
    cooldown: 180,
  },
  {
    // name: {
    //   en: "Fae Guardians",
    //   fr: "Gardiens faë",
    //   de: "Faewächter",
    //   ru: "Волшебные стражи",
    //   cn: "法夜守护者",
    // },
    // guid: 327661,
    // icon: "ability_ardenweald_priest",
    // duraton: 1,
    // cooldown: 90,
    // class: "Priest",
    // cdPlannerMenuActive: false,
  },
];
