export const externalsDB = [
  {
    guid: 47788,
    name: {
      en: "Guardian Spirit",
      de: "Schutzgeist",
      fr: "Esprit gardien",
      ru: "Оберегающий дух",
      ch: "守护之魂",
    },
    wowhead: "https://www.wowhead.com/spell=47788/guardian-spirit",
    icon: require("Images/Classes/Priest/Specialisation/Holy/Icons/GuardianSpiritIcon.jpg").default,
    autoIcon: "spell_holy_guardianspirit",
    external: true,
    include: false,
    cooldown: 180,
  },

  {
    guid: 6940,
    name: {
      en: "Blessing of Sacrifice",
      de: "Segen der Aufopferung",
      fr: "Bénédiction de sacrifice",
      ru: "Жертвенное благословение",
      ch: "牺牲祝福",
    },
    wowhead: "https://www.wowhead.com/spell=6940/blessing-of-sacrifice",
    icon: require("Images/Classes/Paladin/Specialisation/Holy/Icons/BlessingOfSacrifice.jpg").default,
    autoIcon: "spell_holy_sealofsacrifice",
    external: true,
    include: true,
    cooldown: 120,
    reduction: 0.3,
    type: "All", // The type of damage the DR applies to.
  },
  {
    guid: 1022,
    name: {
      en: "Blessing of Protection",
      de: "Segen des Schutzes",
      fr: "Bénédiction de protection",
      ru: "Благословение защиты",
      ch: "保护祝福",
    },
    wowhead: "https://www.wowhead.com/spell=1022/blessing-of-protection",
    icon: require("Images/Classes/Paladin/Specialisation/Holy/Icons/spell_holy_sealofprotection.jpg").default,
    autoIcon: "spell_holy_sealofprotection",
    external: true,
    include: true,
    cooldown: 300,
  },
  {
    guid: 1044,
    name: {
      en: "Blessing of Freedom",
      de: "Segen der Freihei",
      fr: "Bénédiction de liberté",
      ru: "Благословенная свобода",
      ch: "自由祝福",
    },
    wowhead: "https://www.wowhead.com/spell=1044/blessing-of-freedom",
    icon: require("Images/Classes/Paladin/Specialisation/Holy/Icons/spell_holy_sealofvalor.jpg").default,
    autoIcon: "spell_holy_sealofvalor",
    external: true,
    include: false,
    cooldown: 25,
  },
  {
    guid: 633,
    name: {
      en: "Lay on Hands",
      de: "Handauflegung",
      fr: "Imposition des mains",
      ru: "Возложение рук",
      ch: "圣疗术",
    },
    wowhead: "https://www.wowhead.com/spell=633/lay-on-hands",
    icon: require("Images/Classes/Paladin/Specialisation/Holy/Icons/spell_holy_layonhands.jpg").default,
    autoIcon: "spell_holy_layonhands",
    external: true,
    include: false,
    cooldown: 600,
  },
  {
    guid: 102342,
    name: {
      en: "Ironbark",
      de: "Eisenborke",
      fr: "Ecorcefer",
      ru: "Железная кора",
      ch: "铁木树皮",
    },
    wowhead: "https://www.wowhead.com/spell=102342/ironbark",
    icon: require("Images/Classes/Druid/Specialisation/Restoration/Icons/Ironbark.jpg").default,
    autoIcon: "spell_druid_ironbark",
    external: true,
    cooldown: 90,
    reduction: 0.2,
    type: "All", // The type of damage the DR applies to.
    include: true,
  },
  {
    guid: 29166,
    name: {
      en: "Innervate",
      de: "Anregen",
      fr: "Innervation",
      ru: "Озарение",
      ch: "激活",
    },
    wowhead: "https://www.wowhead.com/spell=29166/innervate",
    icon: require("Images/Classes/Druid/Icons/spell_nature_lightning.jpg").default,
    autoIcon: "spell_nature_lightning",
    external: true,
    cooldown: 180,
    include: false,
  },

  {
    guid: 10060,
    name: {
      en: "Power Infusion",
      de: "Seele der Macht",
      fr: "Infusion de puissance",
      ru: "Придание сил",
      ch: "能量灌注",
    },
    wowhead: "https://www.wowhead.com/spell=10060/power-infusion",
    icon: require("Images/Classes/Priest/Specialisation/Discipline/Icons/PowerInfusion.jpg").default,
    autoIcon: "spell_holy_powerinfusion",
    external: true,
    cooldown: 120,
    include: false,
  },

  {
    guid: 116849,
    name: {
      en: "Life Cocoon",
      de: "Lebenskokon",
      fr: "Cocon de vie",
      ru: "Исцеляющий кокон",
      ch: "作茧缚命",
    },
    wowhead: "https://www.wowhead.com/spell=116849/life-cocoon",
    icon: require("Images/Classes/Monk/Specialisation/Mistweaver/Icons/LifeCocoon.jpg").default,
    autoIcon: "spell_monk_diffusemagic",
    external: true,
    cooldown: 120,
    include: false,
  },

  {
    guid: 116841,
    name: {
      en: "Tiger's Lust",
      de: "Tigerrausch",
      fr: "Soif du tigre",
      ru: "Тигриное рвение",
      ch: "迅如猛虎",
    },
    wowhead: "https://www.wowhead.com/spell=116841/tigers-lust",
    icon: require("Images/Classes/Monk/Specialisation/Mistweaver/Icons/ability_monk_tigerslust.jpg").default,
    autoIcon: "ability_monk_tigerslust",
    external: true,
    cooldown: 30,
    include: false,
  },

  {
    guid: 33206,
    name: {
      en: "Pain Suppression",
      de: "Schmerzunterdrückung",
      fr: "Suppression de la douleur",
      ru: "Подавление боли",
      ch: "痛苦压制",
    },
    wowhead: "https://www.wowhead.com/spell=33206/pain-suppression",
    icon: require("Images/Classes/Priest/Specialisation/Discipline/Icons/PainSupression.jpg").default,
    autoIcon: "spell_holy_painsupression",
    external: true,
    cooldown: 180,
    reduction: 0.4,
    type: "All", // The type of damage the DR applies to.
    include: true,
  },

  {
    guid: 357170,
    name: {
      en: "Time Dilation",
      de: "Zeitverschiebung",
      fr: "Dilatation temporelle",
      ru: "Растяжение времени",
      ch: "时间膨胀",
    },
    wowhead: "https://www.wowhead.com/spell=357170/time-dilation",
    icon: require("Images/Classes/Evoker/ability_evoker_timedilation.jpg").default,
    autoIcon: "ability_evoker_timedilation",
    external: true,
    cooldown: 60,
    include: true,
  },
  {
    guid: 374227,
    name: {
      en: "Zephyr",
    },
    wowhead: "https://www.wowhead.com/spell=357170/time-dilation",
    icon: require("Images/Classes/Evoker/ability_evoker_hoverblack.jpg").default,
    autoIcon: "ability_evoker_hoverblack",
    reduction: 0.2,
    type: "aoe",
    external: true,
    include: true,
    cooldown: 60,
  },

];
